import type { BlogPost } from './types'

export const blogPosts: BlogPost[] = [
  {
    id: 'bp-pixel-pitch',
    slug: 'choosing-the-right-led-pixel-pitch',
    title: 'Choosing the Right LED Pixel Pitch for Your Stage',
    categorySlug: 'technical-production',
    excerpt:
      'Pixel pitch is the single most common LED specification mistake we see — here\'s how to think about it in terms of viewing distance, not budget.',
    content: [
      'Pixel pitch — the distance in millimeters between LED clusters — determines how close an audience can stand before individual pixels become visible. It\'s also the specification most frequently chosen for the wrong reason: budget first, viewing distance second. That ordering produces walls that look great in a supplier\'s catalogue photo and slightly grainy in the third row.',
      'The rule of thumb we use internally is straightforward: minimum viewing distance in meters should be roughly equal to the pixel pitch in millimeters. A P2.6 panel reads cleanly from about 2.6 meters back; push an audience closer than that and the image starts to pixelate, no matter how good the content is. For broadcast-facing backdrops, where a camera lens can sit far closer than any human eye, we typically recommend going a full pitch size finer than the in-room math suggests.',
      'The second variable people underweight is content type. A slow-moving brand backdrop with large text tolerates a wider pitch than a data-dense dashboard or fine typography. If your content team is planning detailed charts or small logos, that decision needs to happen before the LED order goes in, not after the wall is built and the content doesn\'t fit.',
      'Finally, viewing distance isn\'t just about the audience — it\'s about the room. A wide, shallow room puts more of your audience close to the stage than a deep, narrow one of the same capacity. We ask for a floor plan before quoting pitch for exactly this reason: two rooms holding the same number of people can call for genuinely different panels.',
      'If you\'re unsure, the safest move is a technical consultation before the LED line item gets locked into a budget. It\'s a fifteen-minute conversation that prevents a visible compromise on event day.',
    ],
    author: 'Kenji Watanabe',
    authorRole: 'Technical Director, LED & Visual Systems',
    publishedAt: '2026-02-18',
    readMinutes: 6,
    visualSeed: 'choosing-the-right-led-pixel-pitch',
  },
  {
    id: 'bp-japan-planning',
    slug: 'planning-events-in-japan-what-international-teams-miss',
    title: 'What International Companies Get Wrong About Planning Events in Japan',
    categorySlug: 'industry-insights',
    excerpt:
      'The mistakes are rarely about culture in the abstract — they\'re about specific, fixable assumptions carried over from events run elsewhere.',
    content: [
      'Most international teams planning their first event in Japan assume the biggest risk is cultural — the wrong gesture, the wrong gift, the wrong tone in an email. In practice, the recurring issues are more mundane and more fixable: venue booking lead times, vendor coordination norms, and how quickly (or slowly) certain approvals move through an organization.',
      'Venue lead times are longer than many international planners expect, particularly for premium hotel ballrooms and convention center halls in Tokyo and Osaka during peak conference season (spring and autumn). Booking six months out is not overcautious for a mid-to-large corporate event; it\'s close to standard practice for the venues international clients most often want.',
      'Vendor coordination is the second gap. In many markets, a client directly manages separate AV, staging, and catering vendors on-site. In Japan, that model creates friction — venues and vendors generally expect a single point of technical and logistical accountability, which is part of why full-service production partners are the norm rather than the exception for events of any real complexity.',
      'The third gap is decision timeline mismatch. Japanese vendor and venue processes often move deliberately through internal approval before confirming details — which can read as slow to a planner used to same-day vendor confirmations elsewhere. Building that lead time into your own internal planning calendar, rather than treating it as a delay to chase, avoids most of the friction we see.',
      'None of this requires a planner to become an expert in Japanese business culture. It requires a local partner who can absorb that translation layer — timeline, vendor norms, approval rhythm — so the event plan reflects how things actually move here, not how they moved at the last event run somewhere else.',
    ],
    author: 'Sarah Whitfield',
    authorRole: 'Director of International Accounts',
    publishedAt: '2026-01-22',
    readMinutes: 7,
    visualSeed: 'planning-events-in-japan-what-international-teams-miss',
  },
  {
    id: 'bp-hybrid-two-teams',
    slug: 'why-hybrid-events-need-two-production-teams',
    title: 'The Hidden Risk in Hybrid Events: Why Two Teams Beat One',
    categorySlug: 'hybrid-virtual',
    excerpt:
      'The most common hybrid event failure isn\'t a technical bug — it\'s one team trying to run the room and the broadcast at the same time.',
    content: [
      'When a hybrid event goes wrong, the postmortem usually points at a piece of technology — a dropped connection, a bad audio feed, a delayed stream. Dig one layer deeper and the actual cause is almost always structural: one stage manager or one technical lead was responsible for both the in-room experience and the broadcast, and when both needed attention at the same moment, one of them lost.',
      'A live room and a live broadcast have different failure modes and different rhythms. The room needs someone watching the audience, the clock, and the speaker. The broadcast needs someone watching stream health, caption sync, and remote audience engagement. These are not the same job, even though they\'re happening during the same event.',
      'Our standard model for any hybrid production splits this explicitly: an in-room stage manager runs the physical event, and a separate broadcast technical director owns the stream, with a shared run-of-show and a communication channel between them, but independent authority over their half of the show. If the stream has an issue, the in-room event doesn\'t stall waiting for a fix. If a speaker runs long, the broadcast team adjusts without needing to interrupt the room.',
      'The cost implication is real — two coordinated leads instead of one — and it\'s also the single highest-leverage line item in a hybrid budget. We\'ve seen more hybrid events saved by this structural split than by any specific piece of redundant hardware, though we build in that hardware redundancy too.',
      'If you\'re evaluating a hybrid event proposal from any vendor, this is the question worth asking directly: who is responsible for the room, and who is responsible for the stream, and are they the same person on the day.',
    ],
    author: 'Kenji Watanabe',
    authorRole: 'Technical Director, LED & Visual Systems',
    publishedAt: '2025-12-09',
    readMinutes: 6,
    visualSeed: 'why-hybrid-events-need-two-production-teams',
  },
  {
    id: 'bp-booking-timeline',
    slug: 'a-practical-timeline-for-booking-event-production',
    title: 'A Practical Timeline for Booking Event Production Services',
    categorySlug: 'event-planning',
    excerpt:
      'How far in advance you actually need to book depends on format and complexity, not a single universal rule — here\'s how we break it down.',
    content: [
      'The honest answer to "how far in advance should I book?" is "it depends," but that\'s not a useful answer on its own, so here\'s how we actually think about it internally when a client asks.',
      'Standard corporate events — a town hall, a client dinner, a single-room conference under 300 people — are comfortably plannable on four to six weeks\' notice. Equipment and crew availability are rarely the constraint at this scale; venue availability usually is.',
      'Multi-session conferences, exhibitions, and anything requiring custom staging or rigging benefit from eight to twelve weeks. This isn\'t about equipment scarcity so much as design time — a good technical plan for a multi-room conference or an exhibition booth takes real iteration, and compressing that timeline compresses the quality of the plan, not just the paperwork.',
      'Award ceremonies, product launches with custom reveal mechanics, and large outdoor events sit at the long end — twelve weeks or more — because they typically involve bespoke elements (custom rigging, reveal staging, broadcast integration) that can\'t be pulled from standard inventory and assembled quickly.',
      'Shorter-notice requests aren\'t automatically out of reach. We take on compressed-timeline projects regularly when our schedule allows, particularly for clients who can move quickly on decisions once a proposal is in hand. The honest version of this conversation is always better than an optimistic one — if a timeline genuinely won\'t work, we\'ll tell you that upfront rather than overpromise and scramble later.',
    ],
    author: 'Aiko Tanaka',
    authorRole: 'Head of Event Planning',
    publishedAt: '2025-11-14',
    readMinutes: 5,
    visualSeed: 'a-practical-timeline-for-booking-event-production',
  },
  {
    id: 'bp-trade-show-buildout',
    slug: 'inside-a-trade-show-build-nine-hour-load-in',
    title: 'Inside a Trade Show Build: What Happens in a Nine-Hour Load-In',
    categorySlug: 'technical-production',
    excerpt:
      'A behind-the-scenes look at how an exhibition booth goes from an empty floor slot to a finished LED and lighting install in under a day.',
    content: [
      'Exhibition halls don\'t hand out extra time. A typical booth build window runs from early morning hall access to a hard doors-open deadline the same day — often nine hours or less for a mid-size booth with LED, lighting, and structural elements. That window doesn\'t move for weather, delayed freight, or a late-arriving crew member, which is why the sequencing matters as much as the equipment.',
      'The first ninety minutes are almost entirely structural: confirming the booth footprint against the floor plan, laying out power drops, and building any raised flooring or structural frame before a single LED panel or light fixture goes up. Rushing this stage to "get to the visible work" faster is the single most common cause of a build running over — a frame that\'s two centimeters off-square costs far more time to fix once LED panels are already hung on it.',
      'LED and lighting installation happens in parallel crews once the structure is confirmed level and square — one team rigging and cabling the LED wall, another running lighting positions and cable management, coordinated so neither crew is waiting on the other. This is where crew experience shows: a well-coordinated two-crew build finishes measurably faster than the same work done sequentially by one team.',
      'The last ninety minutes are calibration and content: color-matching the LED wall, focusing and cueing lighting, and running booth content end to end at least once before hall doors open. We treat this as non-negotiable time, not a buffer to sacrifice if the structural phase ran long — a booth that looks correct to the naked eye but hasn\'t had its content tested live is a common source of first-morning technical issues.',
      'None of this is unique to us — most experienced production teams sequence a build similarly. What varies is discipline under time pressure, which is really just another way of saying: the plan matters less than whether the crew sticks to it when the schedule gets tight.',
    ],
    author: 'Daichi Suzuki',
    authorRole: 'Senior Production Manager',
    publishedAt: '2025-10-30',
    readMinutes: 6,
    visualSeed: 'inside-a-trade-show-build-nine-hour-load-in',
  },
  {
    id: 'bp-interpretation',
    slug: 'simultaneous-interpretation-what-planners-need-to-know',
    title: 'Simultaneous Interpretation: What Event Planners Need to Know',
    categorySlug: 'event-planning',
    excerpt:
      'Interpretation is an audio infrastructure decision as much as a staffing one — and it needs to be planned earlier than most teams expect.',
    content: [
      'Simultaneous interpretation gets treated, too often, as a staffing line item added late in planning — book the interpreters, done. In practice it\'s an audio infrastructure decision that touches booth placement, channel routing, and sometimes room acoustics, and it needs to be part of the technical plan from early on, not bolted on two weeks before the event.',
      'Interpretation booths need sightlines to the stage, acoustic isolation from the room (interpreters are listening critically through headphones while a live PA runs nearby), and a fixed physical footprint that has to be accounted for in the room layout — which means it affects seating capacity and stage sightlines for everyone else in the room too.',
      'On the audio side, interpreted channels route separately from the main program audio, distributed to receivers for anyone who needs a specific language channel. For hybrid events, this gets a layer more complex: remote attendees need access to the same language channels through the streaming platform, which not every platform supports natively — something worth confirming before the platform is chosen, not after.',
      'The planning-timeline implication is real: interpretation booth space, receiver quantities, and platform compatibility are decisions that belong in the initial technical plan, alongside AV and staging — not a follow-up conversation once the room layout is already fixed.',
      'Done well, interpretation is invisible to the audience using it — a clean, reliable channel that just works. Getting there is mostly a matter of treating it as infrastructure from day one rather than a checkbox added at the end.',
    ],
    author: 'Aiko Tanaka',
    authorRole: 'Head of Event Planning',
    publishedAt: '2025-09-25',
    readMinutes: 5,
    visualSeed: 'simultaneous-interpretation-what-planners-need-to-know',
  },
  {
    id: 'bp-inventory-expansion',
    slug: 'total-media-expands-nationwide-equipment-inventory',
    title: 'TOTAL MEDIA Expands Nationwide Equipment Inventory',
    categorySlug: 'company-news',
    excerpt:
      'New fine-pitch LED, outdoor-rated screens, and expanded rigging capacity are now available across our nationwide inventory.',
    content: [
      'We\'ve expanded our equipment inventory this quarter with a focus on two areas clients have been asking for most: finer-pitch indoor LED for broadcast-facing work, and additional outdoor-rated LED and rigging capacity to support larger ceremonies and activations outside the venue walls.',
      'On the LED side, this includes an expanded stock of P1.9 fine-pitch panels for close-viewing and broadcast backdrop applications, alongside additional P4.8 and P6.6 outdoor stock to support larger outdoor footprints without splitting inventory across multiple concurrent events.',
      'Rigging capacity has grown alongside it — additional motorized chain hoists and box truss ground support, which matters most for clients running events at venues without extensive overhead rigging infrastructure already in place.',
      'This expansion is inventory we own and maintain directly, not subcontracted stock brought in for specific jobs, which keeps our maintenance and calibration standards consistent across every event regardless of scale.',
      'If you\'re scoping a project that depends on availability of any of this equipment, reach out early — nationwide inventory helps with scale, but concurrent bookings during peak seasons still benefit from advance planning.',
    ],
    author: 'TOTAL MEDIA Editorial Team',
    authorRole: 'Company News',
    publishedAt: '2026-03-03',
    readMinutes: 3,
    visualSeed: 'total-media-expands-nationwide-equipment-inventory',
  },
  {
    id: 'bp-streaming-redundancy',
    slug: 'why-redundancy-is-the-most-underrated-streaming-line-item',
    title: 'Why Redundancy Is the Most Underrated Line Item in a Streaming Budget',
    categorySlug: 'hybrid-virtual',
    excerpt:
      'Dual internet circuits and backup encoding rarely feel necessary until the exact moment they\'re the only thing standing between you and a dead stream.',
    content: [
      'When budgets get tight on a hybrid or virtual event, redundant streaming infrastructure is one of the first things teams ask to cut. It\'s an understandable instinct — a second internet circuit and backup encoding path add real cost, and most events run without ever needing the backup. That\'s exactly the problem: you only find out whether you needed it after it\'s too late to add.',
      'A single point of failure in a streaming path can be the venue\'s shared internet connection, a single encoder, or a single network switch — and any one of them going down mid-event turns a technical hiccup into a visible, unrecoverable failure in front of a remote audience who has no visibility into what\'s happening on-site.',
      'The standard redundant setup we build isn\'t exotic: a secondary internet circuit (often a different provider or connection type entirely, to avoid a shared point of failure), a backup encoder ready to take over without manual reconfiguration, and a technical director whose job during the live event is specifically to monitor stream health, separate from whoever is running the room.',
      'The cost of this setup is a small fraction of most event budgets, and it\'s asymmetric in a way that\'s easy to underrate: most of the time it does nothing visible at all, and that\'s exactly the outcome you\'re paying for.',
      'If a stream failure would be genuinely costly to your organization — a global product announcement, an investor call, a press event — redundancy isn\'t the line item to cut for savings. It\'s the line item that exists specifically for the day everything else goes right except the one thing you didn\'t plan for.',
    ],
    author: 'Kenji Watanabe',
    authorRole: 'Technical Director, LED & Visual Systems',
    publishedAt: '2025-08-19',
    readMinutes: 5,
    visualSeed: 'why-redundancy-is-the-most-underrated-streaming-line-item',
  },
]
