import type { EquipmentItem } from './types'

export const equipmentItems: EquipmentItem[] = [
  // Indoor LED
  {
    id: 'eq-led-in-p1-9',
    slug: 'indoor-led-p1-9-fine-pitch',
    categorySlug: 'indoor-led',
    name: 'P1.9 Fine-Pitch Indoor LED',
    summary: 'Ultra-fine pitch panel for close-viewing stage backdrops and broadcast-facing displays.',
    description:
      'Our finest indoor pitch, specified for environments where the audience or camera sits close to the wall — broadcast backdrops, boardroom displays, and stage content viewed from the front rows. Seamless cabinet joins hold up under camera close-ups.',
    specs: [
      { label: 'Pixel Pitch', value: '1.9mm' },
      { label: 'Brightness', value: '800 nits' },
      { label: 'Cabinet Size', value: '500 x 500mm' },
      { label: 'Refresh Rate', value: '3840Hz' },
      { label: 'Recommended Viewing Distance', value: '2m+' },
    ],
    applications: ['Broadcast backdrops', 'Boardroom and briefing room displays', 'Close-viewing stage content'],
    availability: 'limited',
    relatedItemSlugs: ['indoor-led-p2-6-standard', 'camera-broadcast-package'],
    visualSeed: 'indoor-led-p1-9-fine-pitch',
  },
  {
    id: 'eq-led-in-p2-6',
    slug: 'indoor-led-p2-6-standard',
    categorySlug: 'indoor-led',
    name: 'P2.6 Indoor LED Panel',
    summary: 'Our most-deployed indoor pitch, balancing image quality and cost for standard stage backdrops.',
    description:
      'The standard specification for keynote and conference stage backdrops, where viewing distance is typically beyond three meters. Lightweight cabinets and quick-lock rigging keep build time down without compromising image quality.',
    specs: [
      { label: 'Pixel Pitch', value: '2.6mm' },
      { label: 'Brightness', value: '1000 nits' },
      { label: 'Cabinet Size', value: '500 x 500mm' },
      { label: 'Refresh Rate', value: '3840Hz' },
      { label: 'Recommended Viewing Distance', value: '3m+' },
    ],
    applications: ['Keynote and conference backdrops', 'Exhibition booth walls', 'Product launch stages'],
    availability: 'in-stock',
    relatedItemSlugs: ['indoor-led-p1-9-fine-pitch', 'indoor-led-p3-9-rental'],
    visualSeed: 'indoor-led-p2-6-standard',
  },
  {
    id: 'eq-led-in-p3-9',
    slug: 'indoor-led-p3-9-rental',
    categorySlug: 'indoor-led',
    name: 'P3.9 Indoor Rental Panel',
    summary: 'High-volume rental panel for large-format indoor walls where distance allows a wider pitch.',
    description:
      'Specified for large indoor walls — exhibition hall centerpieces, gala backdrops — where viewing distance is generous enough that a wider pitch delivers the same perceived quality at lower cost and faster build time.',
    specs: [
      { label: 'Pixel Pitch', value: '3.9mm' },
      { label: 'Brightness', value: '1200 nits' },
      { label: 'Cabinet Size', value: '500 x 1000mm' },
      { label: 'Refresh Rate', value: '1920Hz' },
      { label: 'Recommended Viewing Distance', value: '4m+' },
    ],
    applications: ['Large exhibition hall walls', 'Gala and ceremony backdrops', 'Multi-panel curved configurations'],
    availability: 'in-stock',
    relatedItemSlugs: ['indoor-led-p2-6-standard', 'truss-box-ground-support'],
    visualSeed: 'indoor-led-p3-9-rental',
  },

  // Outdoor LED
  {
    id: 'eq-led-out-p3-9',
    slug: 'outdoor-led-p3-9-weatherproof',
    categorySlug: 'outdoor-led',
    name: 'P3.9 Outdoor Weatherproof Panel',
    summary: 'IP65-rated outdoor panel for daylight-visible ceremonies and activations.',
    description:
      'Sealed for weather and specified for daylight visibility, this panel is our standard for outdoor ceremonies, activations, and stages where the screen needs to hold up against sun, wind, and light rain without a service interruption.',
    specs: [
      { label: 'Pixel Pitch', value: '3.9mm' },
      { label: 'Brightness', value: '5500 nits' },
      { label: 'IP Rating', value: 'IP65 (front & rear)' },
      { label: 'Cabinet Size', value: '500 x 500mm' },
      { label: 'Wind Load Rating', value: 'Engineered per structural review' },
    ],
    applications: ['Outdoor ceremonies', 'Brand activations', 'Festival and public event stages'],
    availability: 'in-stock',
    relatedItemSlugs: ['outdoor-led-p4-8-screen', 'truss-tower-system'],
    visualSeed: 'outdoor-led-p3-9-weatherproof',
  },
  {
    id: 'eq-led-out-p4-8',
    slug: 'outdoor-led-p4-8-screen',
    categorySlug: 'outdoor-led',
    name: 'P4.8 Outdoor LED Screen',
    summary: 'Large-format outdoor screen system for distant viewing and high-brightness daylight conditions.',
    description:
      'Built for large outdoor footprints where viewing distance runs long — outdoor ceremony backdrops, IMAG screens for large audiences, and public-facing brand walls that need to compete with direct sunlight.',
    specs: [
      { label: 'Pixel Pitch', value: '4.8mm' },
      { label: 'Brightness', value: '6000 nits' },
      { label: 'IP Rating', value: 'IP65 (front & rear)' },
      { label: 'Cabinet Size', value: '500 x 1000mm' },
      { label: 'Recommended Viewing Distance', value: '6m+' },
    ],
    applications: ['Large outdoor ceremonies', 'IMAG screens for large audiences', 'Outdoor brand activations'],
    availability: 'in-stock',
    relatedItemSlugs: ['outdoor-led-p3-9-weatherproof', 'camera-ptz-system'],
    visualSeed: 'outdoor-led-p4-8-screen',
  },
  {
    id: 'eq-led-out-p6-6',
    slug: 'outdoor-led-p6-6-wall',
    categorySlug: 'outdoor-led',
    name: 'P6.6 Outdoor LED Wall',
    summary: 'Long-throw outdoor wall for stadium-scale distance and rapid multi-panel deployment.',
    description:
      'The widest outdoor pitch in our inventory, deployed for very large audiences and long viewing distances where rapid multi-panel build time matters as much as brightness — outdoor festivals, large ceremonies, and public gatherings.',
    specs: [
      { label: 'Pixel Pitch', value: '6.6mm' },
      { label: 'Brightness', value: '6500 nits' },
      { label: 'IP Rating', value: 'IP65 (front & rear)' },
      { label: 'Cabinet Size', value: '500 x 1000mm' },
      { label: 'Recommended Viewing Distance', value: '10m+' },
    ],
    applications: ['Stadium-scale outdoor events', 'Large public ceremonies', 'Festival main stage screens'],
    availability: 'limited',
    relatedItemSlugs: ['outdoor-led-p4-8-screen', 'stage-modular-deck'],
    visualSeed: 'outdoor-led-p6-6-wall',
  },

  // Audio
  {
    id: 'eq-audio-line-array',
    slug: 'audio-line-array-pa',
    categorySlug: 'audio',
    name: 'Line Array PA System',
    summary: 'Scalable line array system for even coverage across conference and ceremony spaces.',
    description:
      'Our primary PA system for mid-to-large rooms, configured per event to deliver even coverage front to back without the hot spots and dead zones of point-source speakers. Scales from a single hang to full stereo arrays for larger halls.',
    specs: [
      { label: 'Configuration', value: 'Modular line array, scalable per room' },
      { label: 'Frequency Response', value: '38Hz – 20kHz' },
      { label: 'Max SPL', value: '138dB (array dependent)' },
      { label: 'Rigging', value: 'Flown or ground-stacked' },
    ],
    applications: ['Conference and keynote halls', 'Award ceremonies and galas', 'Multi-purpose venue spaces'],
    availability: 'in-stock',
    relatedItemSlugs: ['audio-digital-mixing-console', 'truss-motorized-hoist'],
    visualSeed: 'audio-line-array-pa',
  },
  {
    id: 'eq-audio-mixing-console',
    slug: 'audio-digital-mixing-console',
    categorySlug: 'audio',
    name: 'Digital Mixing Console',
    summary: 'Multi-channel digital console for live mixing, monitor mixes, and broadcast feeds.',
    description:
      'A digital console platform operated by a dedicated engineer for every event, supporting simultaneous front-of-house mixing, monitor mixes for presenters, and a clean, separate feed for broadcast or recording.',
    specs: [
      { label: 'Channel Count', value: 'Up to 64 input channels' },
      { label: 'Outputs', value: 'FOH, monitor, and broadcast feeds simultaneously' },
      { label: 'Redundancy', value: 'Dual power supply, backup console option' },
      { label: 'Recording', value: 'Multi-track session recording available' },
    ],
    applications: ['Live event mixing', 'Multi-language interpretation routing', 'Broadcast and recording feeds'],
    availability: 'in-stock',
    relatedItemSlugs: ['audio-line-array-pa', 'audio-wireless-microphone-system'],
    visualSeed: 'audio-digital-mixing-console',
  },
  {
    id: 'eq-audio-wireless-mic',
    slug: 'audio-wireless-microphone-system',
    categorySlug: 'audio',
    name: 'Wireless Microphone System',
    summary: 'RF-coordinated wireless handheld, lavalier, and headset microphones for speakers and panels.',
    description:
      'Wireless microphone systems coordinated channel-by-channel against the venue\'s RF environment, avoiding the dropouts and interference common in dense urban venues and multi-vendor events sharing the same spectrum.',
    specs: [
      { label: 'Channel Types', value: 'Handheld, lavalier, headset' },
      { label: 'RF Coordination', value: 'Frequency-coordinated per venue' },
      { label: 'Range', value: 'Up to 100m line-of-sight' },
      { label: 'Battery Management', value: 'Rechargeable with on-site charging station' },
    ],
    applications: ['Panel discussions and Q&A', 'Keynote presentations', 'Award ceremony presenter mics'],
    availability: 'in-stock',
    relatedItemSlugs: ['audio-digital-mixing-console', 'audio-line-array-pa'],
    visualSeed: 'audio-wireless-microphone-system',
  },

  // Lighting
  {
    id: 'eq-lighting-moving-head',
    slug: 'lighting-moving-head-spot',
    categorySlug: 'lighting',
    name: 'Moving Head Spot Fixture',
    summary: 'Programmable moving spot fixture for stage lighting, gobos, and dynamic cueing.',
    description:
      'Our primary fixture for stage and keynote lighting design, capable of precise gobo projection, color changes, and cue-based movement synced to the run-of-show — used for everything from subtle key lighting to full production cueing.',
    specs: [
      { label: 'Output', value: '800W LED engine' },
      { label: 'Color', value: 'Full CMY + color wheel' },
      { label: 'Gobo Wheels', value: '2 rotating + 1 fixed' },
      { label: 'Control Protocol', value: 'DMX / RDM' },
    ],
    applications: ['Stage and keynote lighting', 'Product reveal cueing', 'Award ceremony presentation lighting'],
    availability: 'in-stock',
    relatedItemSlugs: ['lighting-led-wash', 'lighting-console'],
    visualSeed: 'lighting-moving-head-spot',
  },
  {
    id: 'eq-lighting-led-wash',
    slug: 'lighting-led-wash',
    categorySlug: 'lighting',
    name: 'LED Wash Fixture',
    summary: 'Wide-beam LED wash for ambient stage color and architectural venue lighting.',
    description:
      'Provides the broad, even color wash that grounds a stage or venue lighting design — set behind or beside moving spots for depth, or used on its own for ambient gala and reception lighting.',
    specs: [
      { label: 'Output', value: '300W RGBAL LED array' },
      { label: 'Beam Angle', value: '10°–60° zoom' },
      { label: 'Color', value: 'Full RGBAL mixing' },
      { label: 'Control Protocol', value: 'DMX / RDM' },
    ],
    applications: ['Ambient stage wash', 'Architectural venue lighting', 'Gala and reception lighting'],
    availability: 'in-stock',
    relatedItemSlugs: ['lighting-moving-head-spot', 'lighting-console'],
    visualSeed: 'lighting-led-wash',
  },
  {
    id: 'eq-lighting-console',
    slug: 'lighting-console',
    categorySlug: 'lighting',
    name: 'Lighting Console',
    summary: 'Cue-based lighting control console operated live by a dedicated programmer.',
    description:
      'The control hub for every lighting design we build — cues are programmed against your run-of-show in advance and operated live by a lighting technician who can adjust in real time as the event actually unfolds.',
    specs: [
      { label: 'Control Capacity', value: 'Up to 4096 DMX channels' },
      { label: 'Cue Storage', value: 'Unlimited programmable cues' },
      { label: 'Backup', value: 'Redundant console failover available' },
      { label: 'Networking', value: 'Art-Net / sACN' },
    ],
    applications: ['Cue-based stage lighting', 'Multi-fixture architectural control', 'Broadcast-synced lighting programs'],
    availability: 'in-stock',
    relatedItemSlugs: ['lighting-moving-head-spot', 'lighting-led-wash'],
    visualSeed: 'lighting-console',
  },

  // Stage
  {
    id: 'eq-stage-modular-deck',
    slug: 'stage-modular-deck',
    categorySlug: 'stage',
    name: 'Modular Stage Deck System',
    summary: 'Adjustable-height modular decking for stages of virtually any footprint.',
    description:
      'Our standard stage decking system, configurable in height, footprint, and shape to match venue and program requirements — from a simple presentation platform to a full multi-level production stage.',
    specs: [
      { label: 'Deck Size', value: '2m x 1m modules' },
      { label: 'Height Range', value: '0.2m – 2.4m adjustable' },
      { label: 'Load Rating', value: '750kg/m² distributed' },
      { label: 'Surface', value: 'Non-slip, broadcast-black finish' },
    ],
    applications: ['Keynote and conference stages', 'Award ceremony staging', 'Multi-level product launch sets'],
    availability: 'in-stock',
    relatedItemSlugs: ['stage-riser-platform', 'truss-box-ground-support'],
    visualSeed: 'stage-modular-deck',
  },
  {
    id: 'eq-stage-riser',
    slug: 'stage-riser-platform',
    categorySlug: 'stage',
    name: 'Stage Riser Platform',
    summary: 'Freestanding riser platforms for panel discussions, VIP seating, and camera positions.',
    description:
      'Compact, freestanding platforms used to elevate panel seating, VIP tables, or camera positions above the main floor level — quick to deploy without the full structural planning a main stage requires.',
    specs: [
      { label: 'Platform Size', value: '2m x 1m, single or stacked' },
      { label: 'Height Options', value: '0.2m, 0.4m, 0.6m' },
      { label: 'Load Rating', value: '500kg/m² distributed' },
      { label: 'Setup Time', value: 'Under 30 minutes per unit' },
    ],
    applications: ['Panel discussion seating', 'VIP and head-table elevation', 'Camera platform positions'],
    availability: 'in-stock',
    relatedItemSlugs: ['stage-modular-deck', 'stage-runway'],
    visualSeed: 'stage-riser-platform',
  },
  {
    id: 'eq-stage-runway',
    slug: 'stage-runway',
    categorySlug: 'stage',
    name: 'Runway / Catwalk Stage',
    summary: 'Extended runway staging for product reveals, fashion-format presentations, and processional formats.',
    description:
      'Extended, narrow-format staging for events where movement through the space is part of the presentation — product reveal walks, fashion-format shows, and award ceremony processional entrances.',
    specs: [
      { label: 'Standard Length', value: '8m, extendable in 2m sections' },
      { label: 'Width', value: '1.2m standard, 1.8m available' },
      { label: 'Height', value: '0.4m – 0.8m' },
      { label: 'Surface', value: 'Non-slip, camera-matte finish' },
    ],
    applications: ['Product reveal walks', 'Fashion-format presentations', 'Award ceremony processional entrances'],
    availability: 'made-to-order',
    relatedItemSlugs: ['stage-riser-platform', 'lighting-moving-head-spot'],
    visualSeed: 'stage-runway',
  },

  // Truss
  {
    id: 'eq-truss-box-ground',
    slug: 'truss-box-ground-support',
    categorySlug: 'truss',
    name: 'Box Truss Ground Support',
    summary: 'Self-supporting ground-based truss for LED, lighting, and speaker arrays without venue rigging points.',
    description:
      'Used when a venue has no overhead rigging points, or when structural sign-off favors a ground-supported solution — engineered box truss towers and spans that carry LED, lighting, and speaker loads independently.',
    specs: [
      { label: 'Truss Profile', value: '400mm and 520mm box truss' },
      { label: 'Max Span', value: 'Engineered per load and configuration' },
      { label: 'Load Capacity', value: 'Calculated per structural review' },
      { label: 'Base Options', value: 'Weighted base plates or outrigger stabilizers' },
    ],
    applications: ['Venues without overhead rigging', 'Outdoor stage structures', 'LED and speaker support towers'],
    availability: 'in-stock',
    relatedItemSlugs: ['truss-motorized-hoist', 'truss-tower-system'],
    visualSeed: 'truss-box-ground-support',
  },
  {
    id: 'eq-truss-hoist',
    slug: 'truss-motorized-hoist',
    categorySlug: 'truss',
    name: 'Motorized Chain Hoist',
    summary: 'Motorized rigging hoists for flown LED, lighting, and speaker arrays with precise height control.',
    description:
      'Motorized hoists used for flying LED walls, lighting trusses, and line array speakers from venue rigging points, with precision height control for load-in adjustments and safe, controlled strike.',
    specs: [
      { label: 'Load Capacity', value: '500kg – 1000kg per hoist' },
      { label: 'Control', value: 'Synchronized multi-hoist control system' },
      { label: 'Safety', value: 'Certified load limiters and secondary safety cables' },
      { label: 'Speed', value: 'Variable speed with fine adjustment' },
    ],
    applications: ['Flown LED walls', 'Flown lighting trusses', 'Flown line array speaker systems'],
    availability: 'limited',
    relatedItemSlugs: ['truss-box-ground-support', 'audio-line-array-pa'],
    visualSeed: 'truss-motorized-hoist',
  },
  {
    id: 'eq-truss-tower',
    slug: 'truss-tower-system',
    categorySlug: 'truss',
    name: 'Truss Tower System',
    summary: 'Vertical truss towers for lighting positions, speaker delays, and outdoor screen support.',
    description:
      'Freestanding vertical towers used to position lighting fixtures, delay speakers, or support outdoor LED screens at height, independent of the main stage structure.',
    specs: [
      { label: 'Height Range', value: '3m – 12m, sectional' },
      { label: 'Base Footprint', value: 'Weighted or guy-wired, per site conditions' },
      { label: 'Load Capacity', value: 'Calculated per fixture load' },
      { label: 'Wind Rating', value: 'Engineered for outdoor deployment' },
    ],
    applications: ['Outdoor lighting towers', 'Delay speaker positions', 'Outdoor LED screen support'],
    availability: 'in-stock',
    relatedItemSlugs: ['truss-box-ground-support', 'outdoor-led-p3-9-weatherproof'],
    visualSeed: 'truss-tower-system',
  },

  // Projectors
  {
    id: 'eq-proj-20k',
    slug: 'projector-20000-lumen-laser',
    categorySlug: 'projectors',
    name: '20,000 Lumen Laser Projector',
    summary: 'High-lumen laser projector for large-venue backdrops and projection mapping.',
    description:
      'Our highest-output projector, specified for large venues with high ambient light, wide-format screens, or projection mapping onto set pieces and architecture that demands consistent brightness across an uneven surface.',
    specs: [
      { label: 'Brightness', value: '20,000 lumens' },
      { label: 'Resolution', value: '4K UHD (3840 x 2160)' },
      { label: 'Light Source', value: 'Laser phosphor, 20,000hr rated life' },
      { label: 'Lens Options', value: 'Short-throw to long-throw available' },
    ],
    applications: ['Large-venue stage backdrops', 'Projection mapping on set pieces', 'High-ambient-light environments'],
    availability: 'limited',
    relatedItemSlugs: ['projector-10000-lumen-laser', 'stage-modular-deck'],
    visualSeed: 'projector-20000-lumen-laser',
  },
  {
    id: 'eq-proj-10k',
    slug: 'projector-10000-lumen-laser',
    categorySlug: 'projectors',
    name: '10,000 Lumen Laser Projector',
    summary: 'Mid-output laser projector for standard conference and presentation environments.',
    description:
      'A versatile mid-output projector suited to standard conference rooms and presentation stages with controlled ambient light — our most frequently deployed unit for content and presentation projection.',
    specs: [
      { label: 'Brightness', value: '10,000 lumens' },
      { label: 'Resolution', value: '4K UHD (3840 x 2160)' },
      { label: 'Light Source', value: 'Laser phosphor, 20,000hr rated life' },
      { label: 'Lens Options', value: 'Standard zoom lens included' },
    ],
    applications: ['Conference room presentations', 'Content and slide projection', 'Mid-size venue backdrops'],
    availability: 'in-stock',
    relatedItemSlugs: ['projector-20000-lumen-laser', 'projector-short-throw'],
    visualSeed: 'projector-10000-lumen-laser',
  },
  {
    id: 'eq-proj-short-throw',
    slug: 'projector-short-throw',
    categorySlug: 'projectors',
    name: 'Short-Throw Projector',
    summary: 'Short-throw unit for tight venue spaces and stage-front projection without a long lens path.',
    description:
      'Deployed where floor space or ceiling height limits a standard lens throw distance — booth environments, tight stage-front content projection, or spaces where a projector stand can\'t sit far from the screen.',
    specs: [
      { label: 'Brightness', value: '6,500 lumens' },
      { label: 'Resolution', value: 'WUXGA (1920 x 1200)' },
      { label: 'Throw Ratio', value: '0.38:1' },
      { label: 'Light Source', value: 'Laser phosphor' },
    ],
    applications: ['Exhibition booth projection', 'Tight-space stage-front content', 'Low-ceiling venue environments'],
    availability: 'in-stock',
    relatedItemSlugs: ['projector-10000-lumen-laser', 'displays-video-wall'],
    visualSeed: 'projector-short-throw',
  },

  // Displays
  {
    id: 'eq-displays-signage',
    slug: 'displays-55-inch-signage',
    categorySlug: 'displays',
    name: '55" Digital Signage Display',
    summary: 'Freestanding or mounted digital signage display for wayfinding, registration, and information points.',
    description:
      'Our standard signage display for registration desks, wayfinding points, and information stations — supplied with a floor stand or wall mount and content playback support.',
    specs: [
      { label: 'Screen Size', value: '55"' },
      { label: 'Resolution', value: '4K UHD' },
      { label: 'Brightness', value: '500 nits' },
      { label: 'Mounting', value: 'Floor stand or wall mount' },
    ],
    applications: ['Registration and welcome desks', 'Wayfinding and directory signage', 'Sponsor and agenda displays'],
    availability: 'in-stock',
    relatedItemSlugs: ['displays-touch-kiosk', 'displays-video-wall'],
    visualSeed: 'displays-55-inch-signage',
  },
  {
    id: 'eq-displays-kiosk',
    slug: 'displays-touch-kiosk',
    categorySlug: 'displays',
    name: 'Freestanding Touch Kiosk',
    summary: 'Interactive touchscreen kiosk for exhibition engagement and self-service registration.',
    description:
      'An interactive kiosk used for exhibition booth engagement, self-service check-in, and interactive content — deployed standalone or networked across a show floor.',
    specs: [
      { label: 'Screen Size', value: '32" or 43" touch display' },
      { label: 'Touch Technology', value: 'Capacitive multi-touch' },
      { label: 'Connectivity', value: 'Wi-Fi / Ethernet, networkable' },
      { label: 'Housing', value: 'Freestanding, branded wrap available' },
    ],
    applications: ['Exhibition booth engagement', 'Self-service check-in', 'Interactive product showcases'],
    availability: 'in-stock',
    relatedItemSlugs: ['displays-55-inch-signage', 'displays-video-wall'],
    visualSeed: 'displays-touch-kiosk',
  },
  {
    id: 'eq-displays-video-wall',
    slug: 'displays-video-wall',
    categorySlug: 'displays',
    name: 'Video Wall Display',
    summary: 'Modular LCD video wall for a screen-based (non-LED) large-format display option.',
    description:
      'A modular LCD video wall alternative to LED for indoor environments where a screen-based large display is preferred — content-rich exhibition centerpieces and lobby installations.',
    specs: [
      { label: 'Configuration', value: '2x2 to 5x5 modular array' },
      { label: 'Bezel Width', value: '3.5mm ultra-narrow' },
      { label: 'Resolution', value: '4K UHD per module, tiled' },
      { label: 'Mounting', value: 'Freestanding frame or wall-mounted' },
    ],
    applications: ['Exhibition centerpiece displays', 'Lobby and reception installations', 'Content-rich indoor walls'],
    availability: 'in-stock',
    relatedItemSlugs: ['displays-55-inch-signage', 'indoor-led-p2-6-standard'],
    visualSeed: 'displays-video-wall',
  },

  // Cameras
  {
    id: 'eq-camera-ptz',
    slug: 'camera-ptz-system',
    categorySlug: 'cameras',
    name: 'PTZ Camera System',
    summary: 'Remote pan-tilt-zoom cameras for unobtrusive multi-angle coverage without a dedicated operator per camera.',
    description:
      'Remotely controlled PTZ cameras used to add coverage angles — audience shots, wide stage shots, panel close-ups — without staffing a camera operator at every position. Controlled from a central vision panel.',
    specs: [
      { label: 'Output', value: '4K UHD / 1080p60' },
      { label: 'Zoom', value: '20x optical' },
      { label: 'Control', value: 'Centralized PTZ control panel' },
      { label: 'Mounting', value: 'Ceiling, wall, or tripod mount' },
    ],
    applications: ['Panel and audience coverage', 'Unobtrusive multi-angle shots', 'Hybrid and streaming productions'],
    availability: 'in-stock',
    relatedItemSlugs: ['camera-broadcast-package', 'camera-vision-switcher-kit'],
    visualSeed: 'camera-ptz-system',
  },
  {
    id: 'eq-camera-broadcast',
    slug: 'camera-broadcast-package',
    categorySlug: 'cameras',
    name: 'Broadcast Camera Package',
    summary: 'Operator-staffed broadcast cameras for award ceremonies, keynotes, and directed multi-camera productions.',
    description:
      'Full broadcast camera packages with dedicated operators, used for productions where composed, directed shots matter — award ceremonies, keynote coverage, and any event being recorded or streamed as a produced broadcast.',
    specs: [
      { label: 'Output', value: '4K UHD broadcast cameras' },
      { label: 'Crew', value: 'Staffed by trained camera operators' },
      { label: 'Lens Kits', value: 'Zoom and prime lens options' },
      { label: 'Signal', value: 'SDI/fiber transmission to vision switcher' },
    ],
    applications: ['Award ceremony coverage', 'Keynote and stage broadcast', 'Directed multi-camera productions'],
    availability: 'in-stock',
    relatedItemSlugs: ['camera-ptz-system', 'camera-vision-switcher-kit'],
    visualSeed: 'camera-broadcast-package',
  },
  {
    id: 'eq-camera-switcher',
    slug: 'camera-vision-switcher-kit',
    categorySlug: 'cameras',
    name: 'Vision Switcher & Streaming Kit',
    summary: 'Multi-camera vision switching and encoding kit for live production and streaming output.',
    description:
      'The production hub for multi-camera events — switching between camera feeds, integrating graphics and lower-thirds, and encoding the final program for live streaming or broadcast delivery.',
    specs: [
      { label: 'Inputs', value: 'Up to 8 camera/source inputs' },
      { label: 'Output', value: 'Multi-platform streaming encode + program feed' },
      { label: 'Graphics', value: 'Live lower-thirds and overlay integration' },
      { label: 'Redundancy', value: 'Backup encoder and dual internet path' },
    ],
    applications: ['Live streaming production', 'Multi-camera event direction', 'Hybrid event broadcast'],
    availability: 'in-stock',
    relatedItemSlugs: ['camera-broadcast-package', 'camera-ptz-system'],
    visualSeed: 'camera-vision-switcher-kit',
  },

  // Accessories
  {
    id: 'eq-acc-power',
    slug: 'accessories-power-distribution',
    categorySlug: 'accessories',
    name: 'Power Distribution System',
    summary: 'Certified power distribution and circuit management for technical loads of any scale.',
    description:
      'Power distribution engineered and installed to venue code, with redundant circuits allocated to anything broadcast-critical — the infrastructure layer underneath every LED, audio, lighting, and camera system we deploy.',
    specs: [
      { label: 'Distribution', value: 'Three-phase and single-phase distro boards' },
      { label: 'Circuit Protection', value: 'RCD-protected, code-compliant' },
      { label: 'Redundancy', value: 'Isolated backup circuits for critical loads' },
      { label: 'Cable Management', value: 'Rated cabling with full run documentation' },
    ],
    applications: ['Full-event power infrastructure', 'Broadcast-critical redundant circuits', 'Multi-vendor shared power environments'],
    availability: 'in-stock',
    relatedItemSlugs: ['accessories-cable-management', 'truss-motorized-hoist'],
    visualSeed: 'accessories-power-distribution',
  },
  {
    id: 'eq-acc-cable',
    slug: 'accessories-cable-management',
    categorySlug: 'accessories',
    name: 'Cable Ramp & Management Kit',
    summary: 'Cable ramps, dressing, and pathway management for safe, clean cable runs across public areas.',
    description:
      'Cable ramps and dressing systems used to route power and signal cable safely across public walkways and stage areas — a small detail that matters for both safety compliance and a clean production look.',
    specs: [
      { label: 'Ramp Types', value: 'Single, dual, and 5-channel cable ramps' },
      { label: 'Load Rating', value: 'Pedestrian and light vehicle rated' },
      { label: 'Compliance', value: 'Meets venue and fire code walkway requirements' },
      { label: 'Finish', value: 'High-visibility and low-profile options' },
    ],
    applications: ['Public walkway cable crossings', 'Backstage cable dressing', 'Exhibition floor cable management'],
    availability: 'in-stock',
    relatedItemSlugs: ['accessories-power-distribution', 'accessories-flight-cases'],
    visualSeed: 'accessories-cable-management',
  },
  {
    id: 'eq-acc-cases',
    slug: 'accessories-flight-cases',
    categorySlug: 'accessories',
    name: 'Flight Case & Transport Package',
    summary: 'Road-rated flight cases and transport logistics for equipment moving between venues nationwide.',
    description:
      'Road-rated cases and coordinated transport logistics for equipment moving between our facility and venues nationwide, or between multiple event sites on a multi-city program.',
    specs: [
      { label: 'Case Rating', value: 'Road/flight-rated, foam-fitted per equipment set' },
      { label: 'Tracking', value: 'Inventory-tracked per case and event' },
      { label: 'Transport', value: 'Nationwide logistics coordination' },
      { label: 'Insurance', value: 'In-transit coverage included' },
    ],
    applications: ['Multi-city event tours', 'Nationwide equipment logistics', 'Secure equipment transport and storage'],
    availability: 'in-stock',
    relatedItemSlugs: ['accessories-cable-management', 'accessories-power-distribution'],
    visualSeed: 'accessories-flight-cases',
  },
]
