import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 'proj-meridian-summit',
    slug: 'meridian-robotics-apac-summit',
    title: 'APAC Partner Summit',
    client: 'Meridian Robotics',
    location: 'Tokyo',
    year: 2025,
    category: 'Hybrid',
    summary:
      'A two-day hybrid partner summit connecting in-room attendees in Tokyo with remote partners across nine countries and time zones.',
    description: [
      'Meridian Robotics needed their annual APAC partner summit to reach partners who couldn\'t travel to Tokyo without compromising the in-room experience for the 220 attendees who could. We designed the event as two coordinated productions from the start — an in-room stage program and an independent broadcast — rather than adapting a standard conference format after the fact.',
      'A dedicated broadcast technical director ran the stream on redundant dual-circuit internet, separate from the in-room stage management team, while simultaneous interpretation channels carried both Japanese and English audio to in-room and remote attendees alike.',
      'The result held through both days without a streaming interruption, and remote attendees reported engagement levels close to in-room attendees based on Q&A participation — a metric Meridian now tracks as a standard success measure for future hybrid events.',
    ],
    servicesUsed: ['hybrid-events', 'live-streaming', 'technical-production'],
    equipmentUsed: ['camera-vision-switcher-kit', 'audio-digital-mixing-console', 'indoor-led-p2-6-standard'],
    stats: [
      { label: 'Attendees (in-room)', value: '220' },
      { label: 'Remote countries', value: '9' },
      { label: 'Stream uptime', value: '100%' },
    ],
    visualSeed: 'meridian-robotics-apac-summit',
  },
  {
    id: 'proj-ridgeline-expo',
    slug: 'ridgeline-semiconductor-tech-expo',
    title: 'Tech Expo Booth & Product Reveal',
    client: 'Ridgeline Semiconductor',
    location: 'Osaka',
    year: 2025,
    category: 'Exhibition',
    summary:
      'A 120-square-meter exhibition booth with an integrated LED centerpiece and on-floor product reveal, built in a nine-hour load-in window.',
    description: [
      'Ridgeline\'s booth needed to anchor their presence on a crowded show floor while accommodating a scheduled product reveal partway through the first show day — meaning the booth had to function as a standard exhibition space and, for fifteen minutes, as a small stage production.',
      'We built a curved P2.6 indoor LED centerpiece as the booth\'s visual anchor, with a lighting cue sequence pre-programmed for the reveal moment, executed within the hall\'s strict nine-hour build window shared with dozens of neighboring exhibitors.',
      'The booth held its calibration and cueing for the full three-day show, with our technicians on the floor throughout for live support rather than a build-and-leave arrangement.',
    ],
    servicesUsed: ['exhibitions', 'led-solutions', 'product-launches'],
    equipmentUsed: ['indoor-led-p2-6-standard', 'lighting-moving-head-spot', 'displays-touch-kiosk'],
    stats: [
      { label: 'Booth footprint', value: '120m²' },
      { label: 'Build window', value: '9 hours' },
      { label: 'Show duration', value: '3 days' },
    ],
    visualSeed: 'ridgeline-semiconductor-tech-expo',
  },
  {
    id: 'proj-sakura-agm',
    slug: 'sakura-financial-annual-meeting',
    title: 'Annual General Meeting',
    client: 'Sakura Financial Group',
    location: 'Tokyo',
    year: 2026,
    category: 'Corporate',
    summary:
      'A precisely run shareholder AGM with zero tolerance for technical error, broadcast to a secondary overflow room.',
    description: [
      'Shareholder meetings carry a different risk profile than most corporate events — the room notices any hesitation, and there is no second take. Sakura Financial Group\'s AGM required flawless microphone handoffs between board members, exact timing against a legally-reviewed agenda, and a live overflow feed to a secondary room for shareholders beyond the main hall\'s capacity.',
      'We ran wireless microphone coordination tuned specifically to the venue\'s dense RF environment, a redundant audio path to the overflow room, and a stage management team drilled specifically on the board\'s prepared handoff sequence.',
      'The meeting ran to schedule within minutes across a multi-hour agenda, with the overflow feed holding clean audio and video throughout.',
    ],
    servicesUsed: ['corporate-events', 'audio-solutions', 'technical-production'],
    equipmentUsed: ['audio-wireless-microphone-system', 'audio-digital-mixing-console', 'camera-ptz-system'],
    stats: [
      { label: 'Attendees', value: '480' },
      { label: 'Overflow room feed', value: 'Live, redundant' },
      { label: 'Agenda variance', value: 'Under 3 minutes' },
    ],
    visualSeed: 'sakura-financial-annual-meeting',
  },
  {
    id: 'proj-lumen-launch',
    slug: 'lumen-cosmetics-flagship-launch',
    title: 'Flagship Product Launch',
    client: 'Lumen Cosmetics',
    location: 'Tokyo',
    year: 2025,
    category: 'Corporate',
    summary:
      'A press and VIP product launch built around a single choreographed lighting and reveal sequence.',
    description: [
      'Lumen Cosmetics wanted their flagship launch to feel as considered as the product itself — a brief where lighting design carried as much weight as the physical staging. We designed the reveal around a synchronized lighting and LED cue sequence, rehearsed to the second across multiple full run-throughs before doors opened to press and VIP guests.',
      'Multi-camera coverage captured the reveal for same-day press distribution and social assets, positioned to avoid any visible rigging or technical infrastructure in frame.',
      'Post-event, Lumen\'s marketing team used the multi-camera footage directly in their campaign rollout, a secondary benefit of designing the camera plan alongside the lighting plan from the start rather than as an afterthought.',
    ],
    servicesUsed: ['product-launches', 'lighting-solutions', 'stage-production'],
    equipmentUsed: ['lighting-moving-head-spot', 'lighting-led-wash', 'camera-broadcast-package'],
    stats: [
      { label: 'Guests', value: '180 (press & VIP)' },
      { label: 'Reveal cue accuracy', value: 'Frame-exact' },
      { label: 'Camera positions', value: '4' },
    ],
    visualSeed: 'lumen-cosmetics-flagship-launch',
  },
  {
    id: 'proj-nordholm-symposium',
    slug: 'nordholm-pharmaceuticals-research-symposium',
    title: 'International Research Symposium',
    client: 'Nordholm Pharmaceuticals',
    location: 'Yokohama',
    year: 2025,
    category: 'Conference',
    summary:
      'A three-track, two-day medical research symposium with full simultaneous interpretation across all sessions.',
    description: [
      'Nordholm\'s symposium brought together researchers from twelve countries across three parallel session tracks, with simultaneous interpretation required in every room, not just the main stage — a materially larger interpretation footprint than most conferences of similar size.',
      'We built three independently staffed interpretation booths, each with dedicated audio distribution, and stage-managed all three tracks in parallel to keep session changeovers synchronized across rooms so attendees moving between tracks never missed a session opening.',
      'Every keynote and plenary session was also live streamed for researchers unable to travel, with recordings delivered to Nordholm within 48 hours for their internal research archive.',
    ],
    servicesUsed: ['conferences', 'audio-solutions', 'live-streaming'],
    equipmentUsed: ['audio-digital-mixing-console', 'audio-wireless-microphone-system', 'camera-vision-switcher-kit'],
    stats: [
      { label: 'Parallel tracks', value: '3' },
      { label: 'Interpretation booths', value: '3' },
      { label: 'Countries represented', value: '12' },
    ],
    visualSeed: 'nordholm-pharmaceuticals-research-symposium',
  },
  {
    id: 'proj-orbit-groundbreaking',
    slug: 'orbit-mobility-outdoor-groundbreaking',
    title: 'Outdoor Groundbreaking Ceremony',
    client: 'Orbit Mobility',
    location: 'Nagoya',
    year: 2024,
    category: 'Outdoor',
    summary:
      'A daylight outdoor ceremony with a weatherproof LED screen and press-facing broadcast, built on an open construction site.',
    description: [
      'Orbit Mobility\'s new facility groundbreaking took place on an active construction site with no fixed power or structural infrastructure — everything from power distribution to the outdoor stage had to be brought in and engineered for the site conditions.',
      'A weatherproof outdoor LED screen carried live camera coverage of the ceremony to attendees seated at distance, readable clearly in direct midday sun, supported by a freestanding truss tower positioned clear of the ceremonial area.',
      'Contingency planning covered wind loading and a same-day weather shift, both accounted for in the structural rigging plan before the event, not improvised on the day.',
    ],
    servicesUsed: ['corporate-events', 'led-solutions', 'technical-production'],
    equipmentUsed: ['outdoor-led-p3-9-weatherproof', 'truss-tower-system', 'accessories-power-distribution'],
    stats: [
      { label: 'Attendees', value: '150' },
      { label: 'Screen visibility', value: 'Full daylight readable' },
      { label: 'Site power source', value: 'Fully self-supplied' },
    ],
    visualSeed: 'orbit-mobility-outdoor-groundbreaking',
  },
  {
    id: 'proj-vantage-virtual',
    slug: 'vantage-capital-investor-briefing',
    title: 'Global Investor Briefing',
    client: 'Vantage Capital Partners',
    location: 'Tokyo (Studio Production)',
    year: 2026,
    category: 'Virtual',
    summary:
      'A fully virtual quarterly investor briefing produced from a studio set with multi-speaker, multi-market coordination.',
    description: [
      'Vantage Capital\'s quarterly investor briefing runs entirely virtual by design, but the brief was explicit: it should look and feel like a produced broadcast, not a video call. We built a studio set with broadcast lighting and multi-camera coverage, coordinating speakers dialing in from three separate offices alongside two presenters on-set in Tokyo.',
      'A technical rehearsal against the live platform the day before caught a caption-sync issue on one remote speaker\'s connection, resolved before the actual briefing rather than discovered live.',
      'The finished broadcast ran without incident to an investor audience across four continents, with a same-day edited recording delivered for Vantage\'s investor relations archive.',
    ],
    servicesUsed: ['virtual-events', 'live-streaming', 'technical-production'],
    equipmentUsed: ['camera-broadcast-package', 'lighting-led-wash', 'camera-vision-switcher-kit'],
    stats: [
      { label: 'Remote speaker locations', value: '3' },
      { label: 'Investor markets reached', value: '4 continents' },
      { label: 'Technical issues live', value: '0' },
    ],
    visualSeed: 'vantage-capital-investor-briefing',
  },
  {
    id: 'proj-tsukiyo-gala',
    slug: 'tsukiyo-hospitality-anniversary-gala',
    title: '20th Anniversary Gala & Award Ceremony',
    client: 'Tsukiyo Hospitality Group',
    location: 'Kyoto',
    year: 2025,
    category: 'Corporate',
    summary:
      'A formal anniversary gala combining ambient venue lighting design with a broadcast-style award presentation segment.',
    description: [
      'Tsukiyo\'s 20th anniversary gala needed to shift tonally partway through the evening — from ambient reception lighting to a formal, camera-directed award presentation segment recognizing long-serving staff across their properties.',
      'We designed a lighting program with two distinct cue states built into the same rig, transitioning the room\'s mood without a visible reset, and brought in multi-camera coverage specifically for the awards segment to give Tsukiyo a polished internal recording for future use.',
      'The evening\'s run-of-show was held tightly to schedule despite a live program with unpredictable moments — several award recipients spoke longer than scripted, and the stage management team absorbed the variance without visibly disrupting the evening\'s pacing.',
    ],
    servicesUsed: ['award-ceremonies', 'lighting-solutions', 'stage-production'],
    equipmentUsed: ['lighting-led-wash', 'lighting-moving-head-spot', 'camera-broadcast-package'],
    stats: [
      { label: 'Guests', value: '300' },
      { label: 'Lighting cue states', value: '2 distinct programs' },
      { label: 'Award recipients', value: '24' },
    ],
    visualSeed: 'tsukiyo-hospitality-anniversary-gala',
  },
]
