import type { Service } from './types'

export const services: Service[] = [
  {
    id: 's-corporate-events',
    slug: 'corporate-events',
    category: 'event-type',
    name: 'Corporate Events',
    shortDescription:
      'End-to-end planning and technical production for internal and client-facing corporate events of any scale.',
    heroStatement: 'Corporate events, produced the way your organization needs to be seen.',
    overview: [
      'Corporate events carry a brand and an internal culture at the same time — a town hall says as much about a company as a client dinner does. We plan and produce both, working from your objectives and audience rather than a fixed event template.',
      'Our teams handle logistics, venue coordination, technical production, and on-site management as one accountable service, so your internal stakeholders have a single point of contact instead of a coordination burden layered on top of their day job.',
    ],
    capabilities: [
      'Full event planning and project management from brief to strike',
      'Venue sourcing and technical site assessment',
      'Stage, AV, and lighting design suited to the room and audience',
      'On-site event management and run-of-show execution',
      'Bilingual (Japanese/English) coordination for international stakeholders',
      'Post-event reporting and asset handover',
    ],
    process: [
      { title: 'Brief & Objectives', description: 'We start with what the event needs to achieve for your organization, not a generic checklist.' },
      { title: 'Design & Proposal', description: 'A detailed technical and logistical plan with transparent, itemized pricing.' },
      { title: 'Production', description: 'Build, technical rehearsal, and event-day management by the same team that designed it.' },
      { title: 'Strike & Report', description: 'Clean teardown and a post-event summary covering what worked and what to refine next time.' },
    ],
    idealFor: ['Town halls and internal announcements', 'Client appreciation events', 'Leadership offsites', 'Company milestone celebrations'],
    relatedServiceSlugs: ['event-consultation', 'technical-production', 'hybrid-events'],
    relatedEquipmentCategorySlugs: ['audio', 'lighting', 'displays'],
    faqIds: ['faq-lead-time', 'faq-quote-turnaround'],
    seoTitle: 'Corporate Event Production Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Full-service corporate event planning and production across Japan — venue sourcing, technical design, and on-site management from one accountable team.',
  },
  {
    id: 's-conferences',
    slug: 'conferences',
    category: 'event-type',
    name: 'Conferences',
    shortDescription:
      'Multi-session conference production with reliable AV, staging, and run-of-show discipline at scale.',
    heroStatement: 'Conferences run on discipline as much as design — we bring both.',
    overview: [
      'A conference is a schedule under pressure: parallel sessions, speaker changeovers, and an audience that notices every delay. We build the technical infrastructure and the run-of-show discipline to keep that schedule intact.',
      'From single-track keynote conferences to multi-hall programs with breakout rooms, we scale crew, equipment, and stage management to match session count and audience size, not a one-size template.',
    ],
    capabilities: [
      'Main stage and breakout room AV design',
      'Speaker management and presentation handling',
      'Stage management and run-of-show coordination',
      'Simultaneous interpretation booth setup and support',
      'Registration and wayfinding signage integration',
      'Live streaming of keynote and breakout sessions',
    ],
    process: [
      { title: 'Program Mapping', description: 'We map your session schedule to technical requirements room by room.' },
      { title: 'Technical Design', description: 'Stage, AV, and interpretation infrastructure specified to each room\'s size and program.' },
      { title: 'Rehearsal', description: 'Full technical rehearsal with speakers and stage management before doors open.' },
      { title: 'Live Execution', description: 'On-site stage management holding every room to schedule in parallel.' },
    ],
    idealFor: ['Industry and academic conferences', 'Multi-track corporate summits', 'Annual company conferences', 'Partner and dealer conferences'],
    relatedServiceSlugs: ['hybrid-events', 'live-streaming', 'technical-production'],
    relatedEquipmentCategorySlugs: ['audio', 'lighting', 'cameras', 'displays'],
    faqIds: ['faq-staffing-scale', 'faq-international-language'],
    seoTitle: 'Conference Production & Technical Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Multi-session conference production across Japan — stage management, AV design, interpretation support, and live streaming for programs of any scale.',
  },
  {
    id: 's-exhibitions',
    slug: 'exhibitions',
    category: 'event-type',
    name: 'Exhibitions',
    shortDescription:
      'Exhibition and booth technical production built for compressed build/strike windows and hall logistics.',
    heroStatement: 'Exhibitions live or die on the build window. We build to the clock.',
    overview: [
      'Exhibition halls run on tight, non-negotiable build and strike schedules shared across every exhibitor on the floor. Our teams are built for that rhythm — fast, coordinated installs that still meet the technical and visual standard the exhibit deserves.',
      'We manage booth AV, LED, and lighting technical production, and can coordinate directly with hall organizers and general contractors so your team isn\'t chasing three vendors during load-in.',
    ],
    capabilities: [
      'Booth and pavilion LED, AV, and lighting installation',
      'Hall logistics and general contractor coordination',
      'Rapid build/strike crews for compressed windows',
      'Interactive display and digital signage integration',
      'On-site technical support for the duration of the show',
      'Power distribution and cable management to hall code',
    ],
    process: [
      { title: 'Hall & Booth Review', description: 'We review floor plans, power allocation, and hall rules before design begins.' },
      { title: 'Technical Design', description: 'LED, lighting, and AV specified to booth size and sightlines.' },
      { title: 'Build', description: 'Coordinated install crews working the compressed load-in window.' },
      { title: 'Live Support', description: 'Technicians on the floor for the run of the show, not just the install.' },
    ],
    idealFor: ['Trade show exhibitor booths', 'Brand pavilions', 'Public exhibitions and expos', 'Multi-day exhibition programs'],
    relatedServiceSlugs: ['trade-shows', 'led-solutions', 'technical-production'],
    relatedEquipmentCategorySlugs: ['indoor-led', 'outdoor-led', 'displays', 'lighting'],
    faqIds: ['faq-lead-time', 'faq-venue-site-visit'],
    seoTitle: 'Exhibition & Booth Production Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Exhibition and trade show booth technical production across Japan — LED, lighting, and AV installed to compressed build/strike schedules.',
  },
  {
    id: 's-trade-shows',
    slug: 'trade-shows',
    category: 'event-type',
    name: 'Trade Shows',
    shortDescription:
      'Large-scale trade show production covering exhibitor technical services and organizer-side infrastructure.',
    heroStatement: 'Convention-scale trade shows, engineered for volume and repeatability.',
    overview: [
      'Trade shows multiply exhibition complexity across dozens or hundreds of booths, parallel programming, and thousands of attendees. We support both exhibitor-side technical production and, for organizers, show-wide infrastructure like main stage AV and hall-wide signage.',
      'Our staffing model scales to convention-center volume — repeatable booth builds, coordinated crews, and a single technical point of contact for organizers managing many moving parts at once.',
    ],
    capabilities: [
      'Organizer-side main stage and show floor AV',
      'Exhibitor technical services at scale',
      'Multi-crew coordination across large hall footprints',
      'Show-wide digital signage and wayfinding',
      'Live streaming of main stage programming',
      'On-call technical support desk for the duration of the show',
    ],
    process: [
      { title: 'Show Scoping', description: 'We align on organizer infrastructure needs and exhibitor service packages.' },
      { title: 'Resource Planning', description: 'Crew, equipment, and logistics scheduled against the full show timeline.' },
      { title: 'Build & Show Days', description: 'Coordinated multi-crew execution across the hall footprint.' },
      { title: 'Strike', description: 'Structured teardown sequenced to hall move-out deadlines.' },
    ],
    idealFor: ['Industry-wide trade shows', 'Consumer expos', 'Multi-hall convention center events', 'B2B trade fairs'],
    relatedServiceSlugs: ['exhibitions', 'stage-production', 'technical-production'],
    relatedEquipmentCategorySlugs: ['stage', 'truss', 'audio', 'lighting'],
    faqIds: ['faq-staffing-scale', 'faq-lead-time'],
    seoTitle: 'Trade Show Production Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Convention-scale trade show production across Japan — main stage AV, exhibitor technical services, and multi-crew logistics for large shows.',
  },
  {
    id: 's-product-launches',
    slug: 'product-launches',
    category: 'event-type',
    name: 'Product Launches',
    shortDescription:
      'High-impact product launch production where lighting, staging, and reveal mechanics carry the moment.',
    heroStatement: 'A launch has one moment that matters. We build the production around it.',
    overview: [
      'A product launch succeeds or fails on a small number of seconds — the reveal, the first look, the photo that gets shared. We design lighting, staging, and technical sequencing around that moment specifically, then build everything else in support of it.',
      'From press-only previews to large public launches, we treat the reveal mechanics — timing, lighting cues, camera coverage — as the core engineering problem, not a decoration on top of a standard stage build.',
    ],
    capabilities: [
      'Reveal staging and mechanical/lighting cue design',
      'Premium lighting design matched to brand and product',
      'Multi-camera coverage for press and social capture',
      'LED backdrop and projection integration',
      'Press and media logistics coordination',
      'Live streaming for remote press and audiences',
    ],
    process: [
      { title: 'Moment Design', description: 'We define the reveal sequence first, then engineer the production around it.' },
      { title: 'Technical Build', description: 'Lighting, staging, and cue systems built and cued precisely.' },
      { title: 'Full Cue Rehearsal', description: 'The reveal is rehearsed to the second, multiple times, before the room fills.' },
      { title: 'Live Execution', description: 'Cue-perfect execution with camera coverage for press and social assets.' },
    ],
    idealFor: ['Consumer and B2B product reveals', 'Flagship store and showroom openings', 'Press-only preview events', 'Automotive and technology launches'],
    relatedServiceSlugs: ['award-ceremonies', 'lighting-solutions', 'stage-production'],
    relatedEquipmentCategorySlugs: ['lighting', 'indoor-led', 'cameras'],
    faqIds: ['faq-venue-site-visit', 'faq-quote-turnaround'],
    seoTitle: 'Product Launch Event Production in Japan | TOTAL MEDIA',
    seoDescription:
      'Product launch production across Japan — reveal staging, premium lighting design, and multi-camera coverage built around the moment that matters.',
  },
  {
    id: 's-award-ceremonies',
    slug: 'award-ceremonies',
    category: 'event-type',
    name: 'Award Ceremonies',
    shortDescription:
      'Broadcast-quality award ceremony production, from red carpet to stage to livestream.',
    heroStatement: 'Award ceremonies ask for television-grade production in a live room.',
    overview: [
      'Award ceremonies combine formal programming, live presentation, and often broadcast or streaming distribution — closer to a television production than a standard corporate event. We bring the camera, lighting, and stage management discipline that format demands.',
      'We manage the full sequence: arrivals and red carpet, stage presentation with precise cueing for winners and presenters, and, where needed, a clean live broadcast or stream for audiences who aren\'t in the room.',
    ],
    capabilities: [
      'Stage design and presentation lighting',
      'Broadcast-style multi-camera direction and vision switching',
      'Winner and presenter cueing and stage management',
      'Red carpet and arrivals AV support',
      'Live streaming and broadcast delivery',
      'Orchestral or recorded music cue integration',
    ],
    process: [
      { title: 'Program & Run-of-Show', description: 'We build a precise run-of-show against the award sequence and presenter list.' },
      { title: 'Technical Design', description: 'Camera, lighting, and stage cueing systems designed to the format.' },
      { title: 'Full Rehearsal', description: 'A complete run-through with stand-ins before the live ceremony.' },
      { title: 'Live Broadcast', description: 'Directed multi-camera execution with stream/broadcast delivery.' },
    ],
    idealFor: ['Industry and corporate award ceremonies', 'Employee recognition galas', 'Academic and cultural award events', 'Televised or streamed ceremonies'],
    relatedServiceSlugs: ['live-streaming', 'stage-production', 'product-launches'],
    relatedEquipmentCategorySlugs: ['cameras', 'lighting', 'audio'],
    faqIds: ['faq-hybrid-virtual-reliability'],
    seoTitle: 'Award Ceremony Production Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Broadcast-quality award ceremony production across Japan — stage design, multi-camera direction, and live streaming for formal presentation events.',
  },
  {
    id: 's-virtual-events',
    slug: 'virtual-events',
    category: 'event-type',
    name: 'Virtual Events',
    shortDescription:
      'Fully virtual event production with studio-grade presentation and platform integration.',
    heroStatement: 'A virtual event is still a production — treat it like one.',
    overview: [
      'Virtual events fail when they\'re run like a video call instead of a production. We build them like a broadcast: a real studio or set, professional lighting and camera work, and a technical director managing the platform separately from the on-camera talent.',
      'We integrate with the platform of your choice — webinar tools, virtual event platforms, or a custom stream — and manage speaker coordination, Q&A, and content playback so the live experience runs smoothly from the presenter\'s side and the viewer\'s side at once.',
    ],
    capabilities: [
      'Studio and set design for virtual presentation',
      'Multi-camera, multi-speaker production switching',
      'Platform integration (webinar, virtual event, custom stream)',
      'Remote speaker coordination and technical rehearsal',
      'Live Q&A and audience interaction management',
      'Recording and on-demand asset delivery',
    ],
    process: [
      { title: 'Platform & Format Planning', description: 'We confirm the platform, format, and speaker list before technical design.' },
      { title: 'Studio Build', description: 'Set, lighting, and camera production built to broadcast standard.' },
      { title: 'Speaker Rehearsal', description: 'Remote and in-studio speakers rehearsed on the live platform, not a placeholder.' },
      { title: 'Live Direction', description: 'Full production switching and platform monitoring through the live event.' },
    ],
    idealFor: ['Global product announcements', 'Virtual town halls', 'Webinar series requiring production value', 'Remote press events'],
    relatedServiceSlugs: ['hybrid-events', 'live-streaming', 'technical-production'],
    relatedEquipmentCategorySlugs: ['cameras', 'lighting', 'audio'],
    faqIds: ['faq-hybrid-virtual-reliability'],
    seoTitle: 'Virtual Event Production Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Studio-grade virtual event production across Japan — multi-camera direction, platform integration, and speaker coordination for fully remote events.',
  },
  {
    id: 's-hybrid-events',
    slug: 'hybrid-events',
    category: 'event-type',
    name: 'Hybrid Events',
    shortDescription:
      'In-room and remote audiences produced as one coherent event, not two separate ones.',
    heroStatement: 'One event, two audiences — designed together, not bolted together.',
    overview: [
      'Most hybrid events are designed for the room and the stream gets whatever\'s left over. We design for both audiences from the start — camera positions that don\'t block sightlines, audio mixed for the room and the broadcast separately, and content built to work on a screen as well as it works live.',
      'A dedicated technical director manages the remote broadcast independently of the in-room production team, so an issue on one side never becomes an issue on both.',
    ],
    capabilities: [
      'Dual-audience technical and content design',
      'Independent in-room and broadcast production teams',
      'Remote speaker and panel integration',
      'Redundant streaming infrastructure',
      'Interactive tools for remote audience engagement',
      'Simultaneous interpretation for in-room and remote audiences',
    ],
    process: [
      { title: 'Dual-Audience Design', description: 'Content and technical plans built for the room and the stream together.' },
      { title: 'Infrastructure Build', description: 'Redundant broadcast paths and in-room AV built and tested independently.' },
      { title: 'Full Technical Rehearsal', description: 'A live rehearsal against the actual streaming platform, not a sound check.' },
      { title: 'Live Execution', description: 'Parallel in-room and broadcast direction managed by dedicated teams.' },
    ],
    idealFor: ['Conferences with remote attendee tracks', 'Global town halls across time zones', 'Hybrid press events', 'Investor and shareholder meetings'],
    relatedServiceSlugs: ['virtual-events', 'live-streaming', 'conferences'],
    relatedEquipmentCategorySlugs: ['cameras', 'audio', 'displays'],
    faqIds: ['faq-hybrid-virtual-reliability', 'faq-international-language'],
    seoTitle: 'Hybrid Event Production Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Hybrid event production across Japan — in-room and remote audiences designed as one event, with redundant streaming and dedicated broadcast direction.',
  },
  {
    id: 's-live-streaming',
    slug: 'live-streaming',
    category: 'event-type',
    name: 'Live Streaming',
    shortDescription:
      'Broadcast-grade live streaming with redundant infrastructure and dedicated technical direction.',
    heroStatement: 'Streaming infrastructure that treats "live" as a hard requirement.',
    overview: [
      'A dropped stream is a visible failure in a way few other production issues are. We build streaming infrastructure around redundancy by default — dual internet circuits, backup encoding paths, and a technical director whose only job is watching the broadcast, separate from whoever is running the room.',
      'We support single-camera webcast setups through full multi-camera broadcast direction, and integrate with the platform your audience already uses rather than forcing a new one on them.',
    ],
    capabilities: [
      'Multi-camera live production and vision switching',
      'Redundant internet circuits and encoding paths',
      'Platform integration (YouTube Live, Vimeo, custom RTMP, webinar tools)',
      'Live graphics, lower-thirds, and content overlay',
      'Multi-language audio channel streaming',
      'Recording, editing, and on-demand delivery',
    ],
    process: [
      { title: 'Platform & Redundancy Plan', description: 'We confirm the delivery platform and build redundancy into the plan from the start.' },
      { title: 'Technical Build', description: 'Camera, encoding, and network infrastructure installed and load-tested.' },
      { title: 'Rehearsal on the Live Platform', description: 'A full rehearsal against the actual streaming destination, not a local test.' },
      { title: 'Live Broadcast', description: 'Dedicated technical direction monitoring the stream throughout the event.' },
    ],
    idealFor: ['Conference and keynote streaming', 'Press conference broadcasts', 'Award ceremony and ceremony streaming', 'Multi-language broadcast programs'],
    relatedServiceSlugs: ['hybrid-events', 'virtual-events', 'award-ceremonies'],
    relatedEquipmentCategorySlugs: ['cameras', 'audio', 'accessories'],
    faqIds: ['faq-hybrid-virtual-reliability'],
    seoTitle: 'Live Streaming & Broadcast Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Broadcast-grade live streaming across Japan — redundant infrastructure, multi-camera direction, and dedicated technical monitoring for events of any scale.',
  },
  {
    id: 's-led-solutions',
    slug: 'led-solutions',
    category: 'technical',
    name: 'LED Solutions',
    shortDescription:
      'Indoor and outdoor LED wall design, rigging, and content playback engineered to pitch and viewing distance.',
    heroStatement: 'LED that\'s specified to the room, not just rented off a shelf.',
    overview: [
      'The wrong pixel pitch or panel size is one of the most common — and most visible — mistakes in event production. We specify LED to your actual viewing distance, content, and venue rather than defaulting to whatever\'s available.',
      'From fine-pitch indoor walls for close-viewing stage backdrops to weatherproof outdoor screens for ceremonies and activations, we handle rigging, calibration, and content playback as one integrated service.',
    ],
    capabilities: [
      'Pixel-pitch specification matched to viewing distance',
      'Indoor and outdoor, weatherproof LED systems',
      'Curved, angled, and custom-shape LED configurations',
      'Rigging engineering and structural load sign-off',
      'Content playback and media server operation',
      'On-site calibration and color matching',
    ],
    process: [
      { title: 'Viewing & Content Review', description: 'We assess sightlines, viewing distance, and content type to specify the right pitch.' },
      { title: 'Rigging Design', description: 'Structural rigging engineered and load-checked against venue and hardware limits.' },
      { title: 'Build & Calibration', description: 'Panels rigged, calibrated, and color-matched before doors open.' },
      { title: 'Live Operation', description: 'Media server and playback operated live by our technicians.' },
    ],
    idealFor: ['Stage backdrops and keynote screens', 'Exhibition and booth walls', 'Outdoor ceremonies and activations', 'Broadcast and camera-facing displays'],
    relatedServiceSlugs: ['stage-production', 'technical-production', 'exhibitions'],
    relatedEquipmentCategorySlugs: ['indoor-led', 'outdoor-led', 'truss'],
    faqIds: ['faq-equipment-brands', 'faq-venue-site-visit'],
    seoTitle: 'LED Wall Rental & Solutions in Japan | TOTAL MEDIA',
    seoDescription:
      'Indoor and outdoor LED wall solutions across Japan — pitch specification, rigging engineering, and live content playback for stages, booths, and outdoor events.',
  },
  {
    id: 's-audio-solutions',
    slug: 'audio-solutions',
    category: 'technical',
    name: 'Audio Solutions',
    shortDescription:
      'Line array PA, digital mixing, and interpretation audio designed to room acoustics and program type.',
    heroStatement: 'Audio should disappear — you only notice it when it\'s wrong.',
    overview: [
      'Good audio is invisible: even coverage, no feedback, clean intelligibility for speech and music alike. We design PA and mixing systems to the room\'s acoustics and the specific program — a keynote and a live band need genuinely different systems, not the same rig turned up or down.',
      'We also handle the audio infrastructure that\'s easy to overlook until it fails: interpretation channels, wireless microphone coordination in RF-dense venues, and clean feeds for broadcast and recording.',
    ],
    capabilities: [
      'Line array PA design matched to room acoustics',
      'Digital mixing and monitor systems',
      'Wireless microphone RF coordination',
      'Simultaneous interpretation audio distribution',
      'Broadcast and recording audio feeds',
      'Live sound engineering and mixing',
    ],
    process: [
      { title: 'Room & Program Assessment', description: 'We assess room acoustics and program type before specifying the system.' },
      { title: 'System Design', description: 'PA, mixing, and RF plan designed to avoid coverage gaps and interference.' },
      { title: 'Build & Tuning', description: 'System installed and acoustically tuned to the specific room.' },
      { title: 'Live Mixing', description: 'A dedicated engineer mixes live rather than leaving the system unattended.' },
    ],
    idealFor: ['Conference and keynote audio', 'Multilingual events with interpretation', 'Live music and entertainment programs', 'Broadcast and recorded events'],
    relatedServiceSlugs: ['conferences', 'technical-production', 'live-streaming'],
    relatedEquipmentCategorySlugs: ['audio', 'accessories'],
    faqIds: ['faq-equipment-brands'],
    seoTitle: 'Event Audio Systems & Solutions in Japan | TOTAL MEDIA',
    seoDescription:
      'Line array PA, digital mixing, and interpretation audio solutions across Japan, designed to room acoustics and engineered by live audio technicians.',
  },
  {
    id: 's-lighting-solutions',
    slug: 'lighting-solutions',
    category: 'technical',
    name: 'Lighting Solutions',
    shortDescription:
      'Stage, architectural, and ambient lighting design programmed to support the moment, not just illuminate it.',
    heroStatement: 'Lighting sets the tone before a single word is spoken.',
    overview: [
      'Lighting is the fastest way to signal formality, energy, or intimacy to a room before anyone speaks — and one of the most under-specified elements in standard event packages. We design lighting as a storytelling tool, not a default wash.',
      'Our lighting designers program cues around your run-of-show, so transitions between segments — keynote to panel, presentation to reveal — are marked by light, not just a change of slide.',
    ],
    capabilities: [
      'Stage and keynote lighting design',
      'Moving light and architectural wash programming',
      'Cue-based lighting synced to run-of-show',
      'Camera-matched lighting for broadcast and streaming',
      'Ambient and wayfinding lighting for venue spaces',
      'Console programming and live operation',
    ],
    process: [
      { title: 'Mood & Cue Planning', description: 'We map lighting cues to your run-of-show and the tone each segment needs.' },
      { title: 'Design & Fixture Plan', description: 'Fixture selection and rigging plan built to the venue and program.' },
      { title: 'Programming', description: 'Cues programmed and tested against the actual run-of-show before doors open.' },
      { title: 'Live Operation', description: 'A lighting operator runs the cues live, adjusting in real time as needed.' },
    ],
    idealFor: ['Keynote and stage lighting', 'Product reveal and launch lighting', 'Award ceremony presentation lighting', 'Ambient venue and gala lighting'],
    relatedServiceSlugs: ['product-launches', 'stage-production', 'award-ceremonies'],
    relatedEquipmentCategorySlugs: ['lighting', 'truss'],
    faqIds: ['faq-equipment-brands'],
    seoTitle: 'Event Lighting Design & Solutions in Japan | TOTAL MEDIA',
    seoDescription:
      'Stage, architectural, and ambient lighting solutions across Japan — cue-based design programmed to your run-of-show by professional lighting operators.',
  },
  {
    id: 's-stage-production',
    slug: 'stage-production',
    category: 'technical',
    name: 'Stage Production',
    shortDescription:
      'Modular staging, set construction, and structural rigging engineered to venue and program requirements.',
    heroStatement: 'The stage is the one piece of infrastructure everything else stands on.',
    overview: [
      'Every other technical element — LED, lighting, audio, cameras — depends on the stage being structurally sound, correctly sized, and built to the venue\'s actual constraints. We treat staging as engineering first, aesthetics second, though we don\'t compromise on either.',
      'We build modular stage decking, custom set elements, and rigging systems sized to your program, from a simple presentation platform to a multi-level set with integrated LED and rigging.',
    ],
    capabilities: [
      'Modular stage decking and riser systems',
      'Custom set design and construction',
      'Structural rigging engineered to venue load limits',
      'Multi-level and runway stage configurations',
      'Backstage and quick-change infrastructure',
      'Fast build/strike crews for compressed schedules',
    ],
    process: [
      { title: 'Venue & Load Assessment', description: 'We confirm venue floor load, rigging points, and access before design.' },
      { title: 'Structural Design', description: 'Stage and set engineered to program requirements and signed off structurally.' },
      { title: 'Build', description: 'Coordinated crews build to a schedule matched to your load-in window.' },
      { title: 'Strike', description: 'Structured teardown sequenced to venue move-out requirements.' },
    ],
    idealFor: ['Keynote and conference staging', 'Award ceremony and gala staging', 'Product launch sets', 'Trade show main stages'],
    relatedServiceSlugs: ['led-solutions', 'lighting-solutions', 'technical-production'],
    relatedEquipmentCategorySlugs: ['stage', 'truss'],
    faqIds: ['faq-venue-site-visit', 'faq-power-rigging-safety'],
    seoTitle: 'Stage Production & Set Construction in Japan | TOTAL MEDIA',
    seoDescription:
      'Modular staging, custom set construction, and structural rigging across Japan, engineered to venue load limits and built for fast build/strike windows.',
  },
  {
    id: 's-technical-production',
    slug: 'technical-production',
    category: 'technical',
    name: 'Technical Production',
    shortDescription:
      'Integrated technical direction across LED, audio, lighting, staging, and camera systems as one coordinated discipline.',
    heroStatement: 'Someone has to own the whole technical picture. That\'s this service.',
    overview: [
      'Most technical failures at events happen at the seams between disciplines — lighting that clashes with camera exposure, audio that isn\'t synced with video delay, rigging that wasn\'t coordinated between the LED and lighting teams. Technical production is the discipline of owning those seams.',
      'We provide a technical director who coordinates every system — LED, audio, lighting, staging, cameras — as one integrated build, backed by our full equipment inventory and specialist crews for each discipline.',
    ],
    capabilities: [
      'Single technical director owning the full production',
      'Cross-discipline coordination (LED, audio, lighting, staging, camera)',
      'Power distribution and infrastructure planning',
      'Technical rehearsal and cue integration across systems',
      'On-site technical troubleshooting and contingency management',
      'Post-event technical reporting',
    ],
    process: [
      { title: 'Technical Scoping', description: 'We map every technical discipline your event requires into one plan.' },
      { title: 'Integrated Design', description: 'Systems designed together so cues, power, and rigging align across disciplines.' },
      { title: 'Full Technical Rehearsal', description: 'Every system tested together, not just individually.' },
      { title: 'Live Technical Direction', description: 'One technical director owns execution and contingency in real time.' },
    ],
    idealFor: ['Multi-discipline productions of any format', 'Events with complex rigging or power needs', 'Broadcast-integrated live events', 'Clients who want one technical point of contact'],
    relatedServiceSlugs: ['event-consultation', 'stage-production', 'led-solutions'],
    relatedEquipmentCategorySlugs: ['stage', 'truss', 'audio', 'lighting', 'cameras'],
    faqIds: ['faq-power-rigging-safety', 'faq-what-makes-different'],
    seoTitle: 'Technical Event Production Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Integrated technical production across Japan — one technical director coordinating LED, audio, lighting, staging, and camera systems as a single build.',
  },
  {
    id: 's-event-consultation',
    slug: 'event-consultation',
    category: 'technical',
    name: 'Event Consultation',
    shortDescription:
      'Independent technical and production consultation for teams planning events without in-house AV expertise.',
    heroStatement: 'Sometimes the most useful thing we can do is advise before you commit.',
    overview: [
      'Not every engagement needs to start with a full production build. When a team is early in planning — evaluating a venue, sizing a budget, or scoping what "hybrid" would actually require — we offer standalone consultation to get the technical picture right before commitments are made.',
      'This includes venue technical assessments, budget scoping, RFP and vendor-brief support, and second-opinion reviews of technical plans built by another vendor or an internal team.',
    ],
    capabilities: [
      'Venue technical assessment and site walkthroughs',
      'Budget scoping and technical feasibility review',
      'RFP and vendor-brief technical input',
      'Second-opinion review of existing technical plans',
      'Format guidance (in-person, hybrid, or virtual)',
      'Vendor coordination advice for multi-vendor events',
    ],
    process: [
      { title: 'Discovery Call', description: 'We understand your event, constraints, and what decision you\'re trying to make.' },
      { title: 'Assessment', description: 'Venue review, budget scoping, or plan review, depending on your need.' },
      { title: 'Written Recommendation', description: 'A clear, actionable recommendation — not a sales pitch for our own services.' },
      { title: 'Optional Follow-Through', description: 'If you\'d like us to execute, the consultation becomes the basis of the proposal.' },
    ],
    idealFor: ['Teams planning their first hybrid event', 'Internal teams without dedicated AV staff', 'RFP and vendor selection processes', 'Second opinions on existing technical plans'],
    relatedServiceSlugs: ['technical-production', 'corporate-events', 'hybrid-events'],
    relatedEquipmentCategorySlugs: [],
    faqIds: ['faq-what-makes-different', 'faq-quote-turnaround'],
    seoTitle: 'Event Technical Consultation Services in Japan | TOTAL MEDIA',
    seoDescription:
      'Independent event technical consultation across Japan — venue assessments, budget scoping, and second-opinion reviews for teams planning without in-house AV expertise.',
  },
]
