// Generates supabase/migrations/0013_seed_content.sql from the Phase 1
// static content modules, so the schema ships with real content instead of
// an empty database. Deliberately generated, not hand-written — with ~90
// rows and a dozen cross-references, hand transcription is where typos
// live. Run with: node scripts/generate-seed-sql.ts
import { createHash } from 'node:crypto'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { services } from '../src/content/services.ts'
import { solutions } from '../src/content/solutions.ts'
import { equipmentCategories } from '../src/content/equipment-categories.ts'
import { equipmentItems } from '../src/content/equipment.ts'
import { projects } from '../src/content/projects.ts'
import { blogCategories } from '../src/content/blog-categories.ts'
import { blogPosts } from '../src/content/blog-posts.ts'
import { testimonials } from '../src/content/testimonials.ts'
import { clients } from '../src/content/clients.ts'
import { faqs } from '../src/content/faqs.ts'
import { industries } from '../src/content/industries.ts'

const root = path.resolve(import.meta.dirname, '..')

// Deterministic, stable, valid-shaped UUIDs derived from a namespace + the
// content's own natural key (slug or id) — not RFC 4122 v5 compliant, but
// Postgres only needs a syntactically valid UUID, and determinism is what
// lets join-table seed rows reference parent rows without a live database.
function uuidFor(namespace: string, value: string): string {
  const hex = createHash('sha256').update(`${namespace}:${value}`).digest('hex').slice(0, 32)
  const bytes = hex.split('')
  bytes[12] = '5' // version nibble
  bytes[16] = (((parseInt(bytes[16], 16) || 0) & 0x3) | 0x8).toString(16) // variant nibble
  const h = bytes.join('')
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20, 32)}`
}

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return `'${value.replace(/'/g, "''")}'`
}

function int(value: number | null | undefined): string {
  return value === null || value === undefined ? 'null' : String(value)
}

function textArray(values: readonly string[] | undefined): string {
  if (!values || values.length === 0) return "'{}'"
  return `ARRAY[${values.map((v) => str(v)).join(', ')}]::text[]`
}

function jsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`
}

function insert(table: string, columns: string[], rows: string[][]): string {
  if (rows.length === 0) return ''
  const values = rows.map((row) => `  (${row.join(', ')})`).join(',\n')
  return `insert into ${table} (${columns.join(', ')}) values\n${values};\n`
}

const parts: string[] = [
  `-- Generated by scripts/generate-seed-sql.ts from the Phase 1 content in
-- src/content/*.ts — do not hand-edit; change the source content and
-- regenerate instead: node scripts/generate-seed-sql.ts
-- IDs are deterministic (see uuidFor in the generator), so re-running the
-- generator and re-applying this file is idempotent-by-value, though the
-- INSERTs themselves are plain inserts (wrap in a transaction and truncate
-- first if re-seeding a non-empty database).
`,
]

// --- taxonomy -------------------------------------------------------------

parts.push(
  insert(
    'equipment_categories',
    ['id', 'slug', 'name', 'description'],
    equipmentCategories.map((c) => [
      str(uuidFor('equipment_category', c.slug)),
      str(c.slug),
      str(c.name),
      str(c.description),
    ]),
  ),
)

parts.push(
  insert(
    'blog_categories',
    ['id', 'slug', 'name'],
    blogCategories.map((c) => [str(uuidFor('blog_category', c.slug)), str(c.slug), str(c.name)]),
  ),
)

parts.push(
  insert(
    'clients',
    ['id', 'name'],
    clients.map((c) => [str(uuidFor('client', c.id)), str(c.name)]),
  ),
)

parts.push(
  insert(
    'faqs',
    ['id', 'question', 'answer', 'category'],
    faqs.map((f) => [
      str(uuidFor('faq', f.id)),
      str(f.question),
      str(f.answer),
      f.category ? str(f.category) : 'null',
    ]),
  ),
)

parts.push(
  insert(
    'industries',
    ['id', 'slug', 'name', 'description', 'use_cases'],
    industries.map((i) => [
      str(uuidFor('industry', i.slug)),
      str(i.slug),
      str(i.name),
      str(i.description),
      textArray(i.useCases),
    ]),
  ),
)

// --- services & solutions ---------------------------------------------------

parts.push(
  insert(
    'services',
    [
      'id', 'slug', 'category', 'name', 'short_description', 'hero_statement',
      'overview', 'capabilities', 'process', 'ideal_for', 'seo_title', 'seo_description',
    ],
    services.map((s) => [
      str(uuidFor('service', s.slug)),
      str(s.slug),
      str(s.category),
      str(s.name),
      str(s.shortDescription),
      str(s.heroStatement),
      textArray(s.overview),
      textArray(s.capabilities),
      jsonb(s.process),
      textArray(s.idealFor),
      str(s.seoTitle),
      str(s.seoDescription),
    ]),
  ),
)

const serviceRelatedServiceRows: string[][] = []
const serviceRelatedEquipmentCategoryRows: string[][] = []
const serviceFaqRows: string[][] = []
for (const s of services) {
  s.relatedServiceSlugs.forEach((slug, i) =>
    serviceRelatedServiceRows.push([
      str(uuidFor('service', s.slug)),
      str(uuidFor('service', slug)),
      int(i),
    ]),
  )
  s.relatedEquipmentCategorySlugs.forEach((slug, i) =>
    serviceRelatedEquipmentCategoryRows.push([
      str(uuidFor('service', s.slug)),
      str(uuidFor('equipment_category', slug)),
      int(i),
    ]),
  )
  s.faqIds.forEach((faqId, i) =>
    serviceFaqRows.push([str(uuidFor('service', s.slug)), str(uuidFor('faq', faqId)), int(i)]),
  )
}
parts.push(
  insert('service_related_services', ['service_id', 'related_service_id', 'sort_order'], serviceRelatedServiceRows),
)
parts.push(
  insert(
    'service_related_equipment_categories',
    ['service_id', 'equipment_category_id', 'sort_order'],
    serviceRelatedEquipmentCategoryRows,
  ),
)
parts.push(insert('service_faqs', ['service_id', 'faq_id', 'sort_order'], serviceFaqRows))

parts.push(
  insert(
    'solutions',
    ['id', 'slug', 'name', 'short_description', 'hero_statement', 'overview', 'highlights', 'seo_title', 'seo_description'],
    solutions.map((s) => [
      str(uuidFor('solution', s.slug)),
      str(s.slug),
      str(s.name),
      str(s.shortDescription),
      str(s.heroStatement),
      textArray(s.overview),
      jsonb(s.highlights),
      str(s.seoTitle),
      str(s.seoDescription),
    ]),
  ),
)

const solutionServiceRows: string[][] = []
for (const s of solutions) {
  s.includedServiceSlugs.forEach((slug, i) =>
    solutionServiceRows.push([str(uuidFor('solution', s.slug)), str(uuidFor('service', slug)), int(i)]),
  )
}
parts.push(insert('solution_services', ['solution_id', 'service_id', 'sort_order'], solutionServiceRows))

// --- equipment --------------------------------------------------------------

parts.push(
  insert(
    'equipment_items',
    ['id', 'slug', 'category_id', 'name', 'summary', 'description', 'specs', 'applications', 'availability', 'visual_seed'],
    equipmentItems.map((item) => [
      str(uuidFor('equipment_item', item.slug)),
      str(item.slug),
      str(uuidFor('equipment_category', item.categorySlug)),
      str(item.name),
      str(item.summary),
      str(item.description),
      jsonb(item.specs),
      textArray(item.applications),
      str(item.availability),
      str(item.visualSeed),
    ]),
  ),
)

const equipmentRelatedRows: string[][] = []
for (const item of equipmentItems) {
  item.relatedItemSlugs.forEach((slug, i) =>
    equipmentRelatedRows.push([
      str(uuidFor('equipment_item', item.slug)),
      str(uuidFor('equipment_item', slug)),
      int(i),
    ]),
  )
}
parts.push(
  insert('equipment_related_items', ['equipment_item_id', 'related_item_id', 'sort_order'], equipmentRelatedRows),
)

// --- portfolio ----------------------------------------------------------------

parts.push(
  insert(
    'projects',
    ['id', 'slug', 'title', 'client', 'location', 'year', 'category', 'summary', 'description', 'stats', 'visual_seed'],
    projects.map((p) => [
      str(uuidFor('project', p.slug)),
      str(p.slug),
      str(p.title),
      str(p.client),
      str(p.location),
      int(p.year),
      str(p.category),
      str(p.summary),
      textArray(p.description),
      jsonb(p.stats),
      str(p.visualSeed),
    ]),
  ),
)

const projectServiceRows: string[][] = []
const projectEquipmentRows: string[][] = []
for (const p of projects) {
  p.servicesUsed.forEach((slug, i) =>
    projectServiceRows.push([str(uuidFor('project', p.slug)), str(uuidFor('service', slug)), int(i)]),
  )
  p.equipmentUsed.forEach((slug, i) =>
    projectEquipmentRows.push([str(uuidFor('project', p.slug)), str(uuidFor('equipment_item', slug)), int(i)]),
  )
}
parts.push(insert('project_services', ['project_id', 'service_id', 'sort_order'], projectServiceRows))
parts.push(insert('project_equipment', ['project_id', 'equipment_item_id', 'sort_order'], projectEquipmentRows))

// --- blog -----------------------------------------------------------------

parts.push(
  insert(
    'blog_posts',
    ['id', 'slug', 'category_id', 'title', 'excerpt', 'content', 'author', 'author_role', 'published_at', 'read_minutes', 'visual_seed'],
    blogPosts.map((post) => [
      str(uuidFor('blog_post', post.slug)),
      str(post.slug),
      str(uuidFor('blog_category', post.categorySlug)),
      str(post.title),
      str(post.excerpt),
      textArray(post.content),
      str(post.author),
      str(post.authorRole),
      str(post.publishedAt),
      int(post.readMinutes),
      str(post.visualSeed),
    ]),
  ),
)

// --- testimonials -----------------------------------------------------------

parts.push(
  insert(
    'testimonials',
    ['id', 'quote', 'author', 'role', 'company', 'sort_order'],
    testimonials.map((t, i) => [
      str(uuidFor('testimonial', t.id)),
      str(t.quote),
      str(t.author),
      str(t.role),
      str(t.company),
      int(i),
    ]),
  ),
)

const sql = parts.filter(Boolean).join('\n')
const outPath = path.join(root, 'supabase', 'migrations', '0013_seed_content.sql')
await writeFile(outPath, sql)
console.log(`wrote ${path.relative(root, outPath)}`)
