// Same approach as generate-i18n-migration.ts (services/solutions), for the
// taxonomy tables: equipment_categories, blog_categories, faqs, industries.
// Produces 0018_i18n_taxonomy.sql. Run with:
//   node scripts/generate-i18n-migration-taxonomy.ts
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { equipmentCategories } from '../src/content/equipment-categories.ts'
import { blogCategories } from '../src/content/blog-categories.ts'
import { faqs } from '../src/content/faqs.ts'
import { industries } from '../src/content/industries.ts'

const root = path.resolve(import.meta.dirname, '..')

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return `'${value.replace(/'/g, "''")}'`
}

function textArray(values: readonly string[] | undefined): string {
  if (!values || values.length === 0) return "'{}'"
  return `ARRAY[${values.map((v) => str(v)).join(', ')}]::text[]`
}

function alterTwinColumns(
  table: string,
  columns: { old: string; en: string; ja: string; type: 'text' | 'text[]' },
): string {
  const addDefault = columns.type === 'text[]' ? " not null default '{}'" : ''
  const jaType = columns.type === 'text[]' ? 'text[]' : 'text'
  return [
    `alter table ${table} rename column ${columns.old} to ${columns.en};`,
    `alter table ${table} add column ${columns.ja} ${jaType}${addDefault};`,
  ].join('\n')
}

const parts: string[] = [
  `-- Bilingual _ja/_en columns for the taxonomy tables: equipment_categories,
-- blog_categories, faqs, industries. Same pattern as
-- 0017_i18n_services_solutions.sql — see that file's header for the twin-
-- column rationale. Generated by
-- scripts/generate-i18n-migration-taxonomy.ts — do not hand-edit the
-- UPDATE statements below; change the source content files and regenerate.
`,
]

parts.push(alterTwinColumns('equipment_categories', { old: 'name', en: 'name_en', ja: 'name_ja', type: 'text' }))
parts.push(
  alterTwinColumns('equipment_categories', {
    old: 'description',
    en: 'description_en',
    ja: 'description_ja',
    type: 'text',
  }),
)

parts.push(alterTwinColumns('blog_categories', { old: 'name', en: 'name_en', ja: 'name_ja', type: 'text' }))

parts.push(alterTwinColumns('faqs', { old: 'question', en: 'question_en', ja: 'question_ja', type: 'text' }))
parts.push(alterTwinColumns('faqs', { old: 'answer', en: 'answer_en', ja: 'answer_ja', type: 'text' }))

parts.push(alterTwinColumns('industries', { old: 'name', en: 'name_en', ja: 'name_ja', type: 'text' }))
parts.push(
  alterTwinColumns('industries', { old: 'description', en: 'description_en', ja: 'description_ja', type: 'text' }),
)
parts.push(
  alterTwinColumns('industries', { old: 'use_cases', en: 'use_cases_en', ja: 'use_cases_ja', type: 'text[]' }),
)

parts.push('-- Populate Japanese translations for already-seeded rows (matched by slug).')

for (const c of equipmentCategories) {
  parts.push(
    `update equipment_categories set name_ja = ${str(c.nameJa)}, description_ja = ${str(c.descriptionJa)} where slug = ${str(c.slug)};`,
  )
}

for (const c of blogCategories) {
  parts.push(`update blog_categories set name_ja = ${str(c.nameJa)} where slug = ${str(c.slug)};`)
}

for (const f of faqs) {
  parts.push(
    `update faqs set question_ja = ${str(f.questionJa)}, answer_ja = ${str(f.answerJa)} where slug = ${str(f.slug)};`,
  )
}

for (const i of industries) {
  parts.push(
    `update industries set\n` +
      `  name_ja = ${str(i.nameJa)},\n` +
      `  description_ja = ${str(i.descriptionJa)},\n` +
      `  use_cases_ja = ${textArray(i.useCasesJa)}\n` +
      `where slug = ${str(i.slug)};`,
  )
}

const sql = parts.filter(Boolean).join('\n\n') + '\n'
const outPath = path.join(root, 'supabase', 'migrations', '0018_i18n_taxonomy.sql')
await writeFile(outPath, sql)
console.log(`wrote ${path.relative(root, outPath)}`)
