// Same approach as generate-i18n-migration.ts / generate-i18n-migration-taxonomy.ts,
// for equipment_items. Produces 0019_i18n_equipment_items.sql. Run with:
//   node scripts/generate-i18n-migration-equipment.ts
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { equipmentItems } from '../src/content/equipment.ts'

const root = path.resolve(import.meta.dirname, '..')

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return `'${value.replace(/'/g, "''")}'`
}

function textArray(values: readonly string[] | undefined): string {
  if (!values || values.length === 0) return "'{}'"
  return `ARRAY[${values.map((v) => str(v)).join(', ')}]::text[]`
}

function jsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`
}

function alterTwinColumns(
  table: string,
  columns: { old: string; en: string; ja: string; type: 'text' | 'text[]' | 'jsonb' },
): string {
  const addDefault =
    columns.type === 'text[]' ? " not null default '{}'" : columns.type === 'jsonb' ? " not null default '[]'" : ''
  const jaType = columns.type === 'text[]' ? 'text[]' : columns.type === 'jsonb' ? 'jsonb' : 'text'
  return [
    `alter table ${table} rename column ${columns.old} to ${columns.en};`,
    `alter table ${table} add column ${columns.ja} ${jaType}${addDefault};`,
  ].join('\n')
}

const parts: string[] = [
  `-- Bilingual _ja/_en columns for equipment_items. Same pattern as
-- 0017_i18n_services_solutions.sql — see that file's header for the twin-
-- column rationale. specs stays jsonb (array of {label, value}); applications
-- stays text[]. Generated by scripts/generate-i18n-migration-equipment.ts —
-- do not hand-edit the UPDATE statements below; change src/content/equipment.ts
-- and regenerate instead.
`,
]

parts.push(alterTwinColumns('equipment_items', { old: 'name', en: 'name_en', ja: 'name_ja', type: 'text' }))
parts.push(alterTwinColumns('equipment_items', { old: 'summary', en: 'summary_en', ja: 'summary_ja', type: 'text' }))
parts.push(
  alterTwinColumns('equipment_items', { old: 'description', en: 'description_en', ja: 'description_ja', type: 'text' }),
)
parts.push(alterTwinColumns('equipment_items', { old: 'specs', en: 'specs_en', ja: 'specs_ja', type: 'jsonb' }))
parts.push(
  alterTwinColumns('equipment_items', { old: 'applications', en: 'applications_en', ja: 'applications_ja', type: 'text[]' }),
)

parts.push('-- Populate Japanese translations for already-seeded rows (matched by slug).')

for (const item of equipmentItems) {
  parts.push(
    `update equipment_items set\n` +
      `  name_ja = ${str(item.nameJa)},\n` +
      `  summary_ja = ${str(item.summaryJa)},\n` +
      `  description_ja = ${str(item.descriptionJa)},\n` +
      `  specs_ja = ${jsonb(item.specsJa)},\n` +
      `  applications_ja = ${textArray(item.applicationsJa)}\n` +
      `where slug = ${str(item.slug)};`,
  )
}

const sql = parts.filter(Boolean).join('\n\n') + '\n'
const outPath = path.join(root, 'supabase', 'migrations', '0019_i18n_equipment_items.sql')
await writeFile(outPath, sql)
console.log(`wrote ${path.relative(root, outPath)}`)
