// Generates the ALTER TABLE (rename existing col -> *_en, add *_ja) +
// UPDATE (populate *_ja for already-seeded rows, matched by slug) SQL for
// one migration file, from the bilingual src/content/*.ts source of truth.
//
// Deliberately separate from generate-seed-sql.ts / 0013_seed_content.sql —
// that migration is already applied to the live database, so it must never
// be regenerated/reapplied. This script only ever produces NEW migration
// files (0017+) that ALTER existing tables and UPDATE existing rows.
//
// Run with: node scripts/generate-i18n-migration.ts
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { services } from '../src/content/services.ts'
import { solutions } from '../src/content/solutions.ts'

const root = path.resolve(import.meta.dirname, '..')

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return `'${value.replace(/'/g, "''")}'`
}

function textArray(values: readonly string[] | undefined): string {
  if (!values || values.length === 0) return "'{}'"
  return `ARRAY[${values.map((v) => str(v)).join(', ')}]::text[]`
}

function jsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`
}

function alterTwinColumns(
  table: string,
  columns: { old: string; en: string; ja: string; type: 'text' | 'text[]' | 'jsonb' },
): string {
  const addDefault =
    columns.type === 'text[]' ? " not null default '{}'" : columns.type === 'jsonb' ? " not null default '[]'" : ''
  const jaType = columns.type === 'text[]' ? 'text[]' : columns.type === 'jsonb' ? 'jsonb' : 'text'
  return [
    `alter table ${table} rename column ${columns.old} to ${columns.en};`,
    `alter table ${table} add column ${columns.ja} ${jaType}${addDefault};`,
  ].join('\n')
}

const parts: string[] = [
  `-- Bilingual _ja/_en columns for services and solutions.
-- Existing (English) data is renamed to *_en (instant, metadata-only);
-- new *_ja columns are added nullable (scalars) or empty-not-null
-- (arrays/jsonb). *_ja scalars stay permanently nullable — the read-side
-- fallback (ja || en) in content-store.ts is the permanent resilience
-- mechanism, not a temporary migration state.
-- Generated by scripts/generate-i18n-migration.ts — do not hand-edit the
-- UPDATE statements below; change src/content/services.ts / solutions.ts
-- and regenerate instead.
`,
]

for (const [table, cols] of [
  ['services', ['name', 'short_description', 'hero_statement']],
  ['solutions', ['name', 'short_description', 'hero_statement']],
] as const) {
  for (const col of cols) {
    parts.push(alterTwinColumns(table, { old: col, en: `${col}_en`, ja: `${col}_ja`, type: 'text' }))
  }
}

parts.push(alterTwinColumns('services', { old: 'overview', en: 'overview_en', ja: 'overview_ja', type: 'text[]' }))
parts.push(alterTwinColumns('services', { old: 'capabilities', en: 'capabilities_en', ja: 'capabilities_ja', type: 'text[]' }))
parts.push(alterTwinColumns('services', { old: 'process', en: 'process_en', ja: 'process_ja', type: 'jsonb' }))
parts.push(alterTwinColumns('services', { old: 'ideal_for', en: 'ideal_for_en', ja: 'ideal_for_ja', type: 'text[]' }))
parts.push(alterTwinColumns('services', { old: 'seo_title', en: 'seo_title_en', ja: 'seo_title_ja', type: 'text' }))
parts.push(alterTwinColumns('services', { old: 'seo_description', en: 'seo_description_en', ja: 'seo_description_ja', type: 'text' }))

parts.push(alterTwinColumns('solutions', { old: 'overview', en: 'overview_en', ja: 'overview_ja', type: 'text[]' }))
parts.push(alterTwinColumns('solutions', { old: 'highlights', en: 'highlights_en', ja: 'highlights_ja', type: 'jsonb' }))
parts.push(alterTwinColumns('solutions', { old: 'seo_title', en: 'seo_title_en', ja: 'seo_title_ja', type: 'text' }))
parts.push(alterTwinColumns('solutions', { old: 'seo_description', en: 'seo_description_en', ja: 'seo_description_ja', type: 'text' }))

parts.push('-- Populate Japanese translations for already-seeded rows (matched by slug).')

for (const s of services) {
  parts.push(
    `update services set\n` +
      `  name_ja = ${str(s.nameJa)},\n` +
      `  short_description_ja = ${str(s.shortDescriptionJa)},\n` +
      `  hero_statement_ja = ${str(s.heroStatementJa)},\n` +
      `  overview_ja = ${textArray(s.overviewJa)},\n` +
      `  capabilities_ja = ${textArray(s.capabilitiesJa)},\n` +
      `  process_ja = ${jsonb(s.processJa)},\n` +
      `  ideal_for_ja = ${textArray(s.idealForJa)},\n` +
      `  seo_title_ja = ${str(s.seoTitleJa)},\n` +
      `  seo_description_ja = ${str(s.seoDescriptionJa)}\n` +
      `where slug = ${str(s.slug)};`,
  )
}

for (const s of solutions) {
  parts.push(
    `update solutions set\n` +
      `  name_ja = ${str(s.nameJa)},\n` +
      `  short_description_ja = ${str(s.shortDescriptionJa)},\n` +
      `  hero_statement_ja = ${str(s.heroStatementJa)},\n` +
      `  overview_ja = ${textArray(s.overviewJa)},\n` +
      `  highlights_ja = ${jsonb(s.highlightsJa)},\n` +
      `  seo_title_ja = ${str(s.seoTitleJa)},\n` +
      `  seo_description_ja = ${str(s.seoDescriptionJa)}\n` +
      `where slug = ${str(s.slug)};`,
  )
}

const sql = parts.filter(Boolean).join('\n\n') + '\n'
const outPath = path.join(root, 'supabase', 'migrations', '0017_i18n_services_solutions.sql')
await writeFile(outPath, sql)
console.log(`wrote ${path.relative(root, outPath)}`)
