-- Bilingual _ja/_en columns for services and solutions.
-- Existing (English) data is renamed to *_en (instant, metadata-only);
-- new *_ja columns are added nullable (scalars) or empty-not-null
-- (arrays/jsonb). *_ja scalars stay permanently nullable — the read-side
-- fallback (ja || en) in content-store.ts is the permanent resilience
-- mechanism, not a temporary migration state.
-- Generated by scripts/generate-i18n-migration.ts — do not hand-edit the
-- UPDATE statements below; change src/content/services.ts / solutions.ts
-- and regenerate instead.


alter table services rename column name to name_en;
alter table services add column name_ja text;

alter table services rename column short_description to short_description_en;
alter table services add column short_description_ja text;

alter table services rename column hero_statement to hero_statement_en;
alter table services add column hero_statement_ja text;

alter table solutions rename column name to name_en;
alter table solutions add column name_ja text;

alter table solutions rename column short_description to short_description_en;
alter table solutions add column short_description_ja text;

alter table solutions rename column hero_statement to hero_statement_en;
alter table solutions add column hero_statement_ja text;

alter table services rename column overview to overview_en;
alter table services add column overview_ja text[] not null default '{}';

alter table services rename column capabilities to capabilities_en;
alter table services add column capabilities_ja text[] not null default '{}';

alter table services rename column process to process_en;
alter table services add column process_ja jsonb not null default '[]';

alter table services rename column ideal_for to ideal_for_en;
alter table services add column ideal_for_ja text[] not null default '{}';

alter table services rename column seo_title to seo_title_en;
alter table services add column seo_title_ja text;

alter table services rename column seo_description to seo_description_en;
alter table services add column seo_description_ja text;

alter table solutions rename column overview to overview_en;
alter table solutions add column overview_ja text[] not null default '{}';

alter table solutions rename column highlights to highlights_en;
alter table solutions add column highlights_ja jsonb not null default '[]';

alter table solutions rename column seo_title to seo_title_en;
alter table solutions add column seo_title_ja text;

alter table solutions rename column seo_description to seo_description_en;
alter table solutions add column seo_description_ja text;

-- Populate Japanese translations for already-seeded rows (matched by slug).

update services set
  name_ja = '企業イベント',
  short_description_ja = '社内向け・対クライアント向けを問わず、あらゆる規模の企業イベントの企画から技術制作までワンストップで対応します。',
  hero_statement_ja = '御社が伝えたい姿を、そのまま形にする企業イベント制作。',
  overview_ja = ARRAY['企業イベントは、ブランドと社内文化を同時に映し出します。タウンホールミーティングもクライアント向けディナーも、その企業を語る場であることに変わりはありません。私たちは定型のイベントテンプレートではなく、貴社の目的とオーディエンスから出発して、その両方を企画・制作します。', 'ロジスティクス、会場調整、技術制作、当日運営を、責任を持つ単一のサービスとして担当します。社内のご担当者様には、日々の業務に上乗せされる調整の負担ではなく、単一の窓口をご用意します。']::text[],
  capabilities_ja = ARRAY['要件定義から撤収まで、企画・プロジェクトマネジメントを一貫して対応', '会場選定と技術面での現地調査', '会場とオーディエンスに合わせたステージ・AV・照明設計', '当日の現地運営とプログラム進行管理', '海外関係者向けの日本語・英語バイリンガルコーディネーション', 'イベント後のレポーティングと資料の引き渡し']::text[],
  process_ja = '[{"title":"要件定義","description":"定型チェックリストではなく、貴社にとってそのイベントが達成すべきことからヒアリングします。"},{"title":"設計・ご提案","description":"詳細な技術・ロジスティクスプランと、項目別に明示した透明な見積もりをご提示します。"},{"title":"制作","description":"設計を担当したチームがそのまま設営・技術リハーサル・当日運営まで担当します。"},{"title":"撤収・レポート","description":"丁寧な撤収作業と、成果および次回への改善点をまとめた事後レポートをお渡しします。"}]'::jsonb,
  ideal_for_ja = ARRAY['タウンホールミーティング・社内発表', 'クライアント向け謝恩イベント', '経営層のオフサイトミーティング', '会社の節目を祝う式典']::text[],
  seo_title_ja = '日本国内の企業イベント制作サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国で企業イベントの企画・制作をワンストップで提供。会場選定、技術設計、当日運営まで責任を持つ単一のチームが担当します。'
where slug = 'corporate-events';

update services set
  name_ja = 'カンファレンス',
  short_description_ja = '複数セッションから成るカンファレンスに対応。信頼性の高いAV、ステージ、進行管理を規模に応じて提供します。',
  hero_statement_ja = 'カンファレンスの成否は設計力と運営規律の両方で決まります。私たちはその両方を提供します。',
  overview_ja = ARRAY['カンファレンスは常に時間との勝負です。並行セッション、登壇者の入れ替え、そしてわずかな遅延にも気づく参加者。私たちはそのスケジュールを守り抜くための技術基盤と進行管理体制を構築します。', '単一トラックの基調講演型カンファレンスから、複数会場・ブレイクアウトルームを伴う大規模プログラムまで、セッション数とオーディエンス規模に応じてクルー・機材・ステージマネジメントをスケールさせます。画一的なテンプレートは使いません。']::text[],
  capabilities_ja = ARRAY['メインステージ・ブレイクアウトルームのAV設計', '登壇者対応とプレゼンテーション管理', 'ステージマネジメントと進行調整', '同時通訳ブースの設営・運用サポート', '受付・サイン計画の統合', '基調講演・ブレイクアウトセッションのライブ配信']::text[],
  process_ja = '[{"title":"プログラム設計","description":"セッションスケジュールを会場ごとの技術要件に落とし込みます。"},{"title":"技術設計","description":"各会場の規模とプログラムに合わせて、ステージ・AV・通訳設備を仕様化します。"},{"title":"リハーサル","description":"開場前に登壇者・ステージマネジメントを含めた本番同様のリハーサルを実施します。"},{"title":"本番運営","description":"複数会場を並行してスケジュール通りに進行させる現地ステージマネジメントを行います。"}]'::jsonb,
  ideal_for_ja = ARRAY['業界カンファレンス・学術会議', '複数トラックの企業サミット', '年次カンファレンス', 'パートナー・代理店向けカンファレンス']::text[],
  seo_title_ja = '日本国内のカンファレンス制作・技術サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国でマルチセッション型カンファレンスの制作に対応。ステージマネジメント、AV設計、通訳サポート、ライブ配信まであらゆる規模に対応します。'
where slug = 'conferences';

update services set
  name_ja = '展示会',
  short_description_ja = '限られた搬入出時間とホールのロジスティクスに対応した、展示会・ブースの技術制作。',
  hero_statement_ja = '展示会の成否は搬入時間で決まります。私たちは時間に正確に施工します。',
  overview_ja = ARRAY['展示会場は、すべての出展社が共有する厳格な搬入出スケジュールで運営されます。私たちのチームはそのリズムに合わせて、迅速かつ統率の取れた施工を、展示にふさわしい技術・ビジュアル品質を保ちながら実現します。', 'ブースのAV・LED・照明の技術制作を担当し、会場主催者やゼネコンとも直接調整可能です。搬入時に貴社が複数のベンダーを掛け持ちで管理する必要はありません。']::text[],
  capabilities_ja = ARRAY['ブース・パビリオンのLED・AV・照明施工', '会場ロジスティクスとゼネコンとの調整', '短時間搬入出に対応する迅速な施工クルー', 'インタラクティブディスプレイ・デジタルサイネージの統合', '会期中の現地技術サポート', '会場規定に準拠した電源分配・配線管理']::text[],
  process_ja = '[{"title":"会場・ブース確認","description":"設計前にフロアプラン、電源配分、会場規定を確認します。"},{"title":"技術設計","description":"ブースサイズと視認性に合わせてLED・照明・AVを仕様化します。"},{"title":"施工","description":"限られた搬入時間の中で、統率の取れた施工クルーが作業します。"},{"title":"会期中サポート","description":"施工後も会期を通じて技術者が現場に常駐します。"}]'::jsonb,
  ideal_for_ja = ARRAY['見本市の出展ブース', 'ブランドパビリオン', '一般公開の展示会・博覧会', '複数日にわたる展示会プログラム']::text[],
  seo_title_ja = '日本国内の展示会・ブース制作サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国で展示会・見本市ブースの技術制作に対応。限られた搬入出時間の中でLED・照明・AVを施工します。'
where slug = 'exhibitions';

update services set
  name_ja = '見本市',
  short_description_ja = '大規模見本市に対応。出展社向け技術サービスと主催者側インフラの両方をカバーします。',
  hero_statement_ja = 'コンベンション規模の見本市を、量と再現性に耐えるよう設計します。',
  overview_ja = ARRAY['見本市では、数十から数百のブース、並行プログラム、数千人規模の来場者によって展示会の複雑さが何倍にも増します。私たちは出展社側の技術制作に加え、主催者側のメインステージAVや会場全体のサイン計画といったインフラも支援します。', 'コンベンションセンター規模に対応できる人員体制を整えており、再現性のあるブース施工、統率されたクルー、そして多くの変動要素を同時に管理する主催者様のための単一の技術窓口を提供します。']::text[],
  capabilities_ja = ARRAY['主催者側のメインステージ・会場フロアAV', '大規模対応の出展社向け技術サービス', '広大な会場における複数クルーの統率', '会場全体のデジタルサイネージ・案内サイン', 'メインステージプログラムのライブ配信', '会期中常駐の技術サポートデスク']::text[],
  process_ja = '[{"title":"要件整理","description":"主催者様のインフラ要件と出展社向けサービスパッケージをすり合わせます。"},{"title":"リソース計画","description":"会期全体のタイムラインに合わせてクルー・機材・ロジスティクスを計画します。"},{"title":"施工・会期運営","description":"会場全体で複数クルーを統率し運営します。"},{"title":"撤収","description":"会場の搬出期限に合わせて計画的に撤収します。"}]'::jsonb,
  ideal_for_ja = ARRAY['業界全体の見本市', '一般消費者向け博覧会', '複数ホールを使うコンベンションセンターイベント', 'B2B見本市']::text[],
  seo_title_ja = '日本国内の見本市制作サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国でコンベンション規模の見本市制作に対応。メインステージAV、出展社向け技術サービス、複数クルーによるロジスティクスまで大規模イベントを支援します。'
where slug = 'trade-shows';

update services set
  name_ja = '製品発表会',
  short_description_ja = '照明・ステージ・演出ギミックがその瞬間を支える、インパクトのある製品発表会制作。',
  hero_statement_ja = '発表会には決定的な瞬間が一つあります。私たちはその瞬間を中心に制作を組み立てます。',
  overview_ja = ARRAY['製品発表会の成否は、わずか数秒の「お披露目」「最初の一目」「拡散される写真」で決まります。私たちはその瞬間を中心に照明・ステージ・技術演出のタイミングを設計し、それ以外の要素はすべてその瞬間を支えるために構築します。', 'プレス限定のプレビューから大規模な一般公開発表会まで、タイミング・照明キュー・カメラワークといった演出ギミックを、通常のステージ施工に付随する装飾ではなく、中核となるエンジニアリング課題として扱います。']::text[],
  capabilities_ja = ARRAY['お披露目演出とメカニカル・照明キューの設計', 'ブランド・製品に合わせたプレミアム照明設計', 'プレス・SNS向けのマルチカメラ撮影', 'LED背景・プロジェクションの統合', 'プレス・メディア対応のロジスティクス調整', 'リモート参加のプレス・視聴者向けライブ配信']::text[],
  process_ja = '[{"title":"演出設計","description":"まずお披露目のシーケンスを定義し、そこから制作全体を設計します。"},{"title":"技術施工","description":"照明・ステージ・キューシステムを精緻に構築します。"},{"title":"本番リハーサル","description":"開場前に、秒単位でお披露目シーンを複数回リハーサルします。"},{"title":"本番運営","description":"プレス・SNS向け撮影も含め、キュー通りに正確に本番を運営します。"}]'::jsonb,
  ideal_for_ja = ARRAY['一般・B2B向け製品発表', '旗艦店・ショールームのオープニング', 'プレス限定プレビューイベント', '自動車・テクノロジー製品の発表会']::text[],
  seo_title_ja = '日本国内の製品発表会イベント制作 | TOTAL MEDIA',
  seo_description_ja = '日本全国で製品発表会の制作に対応。決定的な瞬間を中心に、お披露目演出、プレミアム照明設計、マルチカメラ撮影を構築します。'
where slug = 'product-launches';

update services set
  name_ja = '授賞式',
  short_description_ja = 'レッドカーペットからステージ、ライブ配信まで、放送品質の授賞式制作。',
  hero_statement_ja = '授賞式には、生の会場でテレビ品質の制作が求められます。',
  overview_ja = ARRAY['授賞式は、フォーマルなプログラム進行、生のプレゼンテーション、そして放送や配信を伴うことが多く、通常の企業イベントよりもテレビ番組制作に近い性質を持ちます。私たちはその形式が求めるカメラワーク・照明・ステージマネジメントの規律を提供します。', '到着・レッドカーペットから、受賞者・プレゼンターの正確なキューに基づくステージ進行、そして必要に応じて会場外の視聴者向けのクリーンなライブ放送・配信まで、一連の流れを管理します。']::text[],
  capabilities_ja = ARRAY['ステージデザインとプレゼンテーション照明', '放送品質のマルチカメラディレクション・スイッチング', '受賞者・プレゼンターのキュー出しとステージマネジメント', 'レッドカーペット・到着シーンのAVサポート', 'ライブ配信・放送素材の納品', 'オーケストラ演奏・収録音源のキュー統合']::text[],
  process_ja = '[{"title":"プログラム・進行台本","description":"受賞順序とプレゼンター一覧に基づき、精緻な進行台本を作成します。"},{"title":"技術設計","description":"式典の形式に合わせてカメラ・照明・ステージキューシステムを設計します。"},{"title":"本番リハーサル","description":"本番前に代役を立てた通し稽古を実施します。"},{"title":"本番放送","description":"ディレクション付きマルチカメラ運営と配信・放送素材の納品を行います。"}]'::jsonb,
  ideal_for_ja = ARRAY['業界・企業の授賞式', '社員表彰ガラ', '学術・文化系の表彰イベント', 'テレビ放送・配信を伴う式典']::text[],
  seo_title_ja = '日本国内の授賞式制作サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国で放送品質の授賞式制作に対応。ステージデザイン、マルチカメラディレクション、ライブ配信までフォーマルな式典を支援します。'
where slug = 'award-ceremonies';

update services set
  name_ja = 'バーチャルイベント',
  short_description_ja = 'スタジオ品質のプレゼンテーションとプラットフォーム統合による、完全バーチャルイベント制作。',
  hero_statement_ja = 'バーチャルイベントも、れっきとした制作物です。私たちはそのように扱います。',
  overview_ja = ARRAY['バーチャルイベントは、単なるビデオ通話として運営すると失敗します。私たちは実際のスタジオやセット、プロによる照明・カメラワーク、そして出演者とは別にプラットフォームを管理するテクニカルディレクターを配置し、放送番組として制作します。', 'ウェビナーツール、バーチャルイベントプラットフォーム、カスタム配信など、貴社が選ぶプラットフォームに統合します。登壇者対応、Q&A、コンテンツ再生を管理し、登壇者側・視聴者側の双方でスムーズな体験を実現します。']::text[],
  capabilities_ja = ARRAY['バーチャルプレゼンテーション向けスタジオ・セットデザイン', 'マルチカメラ・複数登壇者対応のスイッチング', 'プラットフォーム統合（ウェビナー、バーチャルイベント、カスタム配信）', 'リモート登壇者の調整と技術リハーサル', 'ライブQ&Aと視聴者インタラクション管理', '収録・オンデマンド素材の納品']::text[],
  process_ja = '[{"title":"プラットフォーム・形式確認","description":"技術設計前にプラットフォーム、形式、登壇者リストを確認します。"},{"title":"スタジオ施工","description":"放送基準でセット・照明・カメラワークを構築します。"},{"title":"登壇者リハーサル","description":"リモート・スタジオ内の登壇者を、仮のツールではなく本番プラットフォームでリハーサルします。"},{"title":"本番ディレクション","description":"本番を通じて制作スイッチングとプラットフォーム監視を行います。"}]'::jsonb,
  ideal_for_ja = ARRAY['グローバル製品発表', 'バーチャルタウンホール', '制作品質が求められるウェビナーシリーズ', 'リモートプレスイベント']::text[],
  seo_title_ja = '日本国内のバーチャルイベント制作サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国でスタジオ品質のバーチャルイベント制作に対応。マルチカメラディレクション、プラットフォーム統合、登壇者調整まで完全リモートイベントを支援します。'
where slug = 'virtual-events';

update services set
  name_ja = 'ハイブリッドイベント',
  short_description_ja = '会場参加者とリモート参加者を、別々のイベントではなく一つの体験として制作します。',
  hero_statement_ja = '一つのイベント、二つのオーディエンス。後付けではなく、最初から一体で設計します。',
  overview_ja = ARRAY['多くのハイブリッドイベントは会場向けに設計され、配信は残りのリソースで対応されがちです。私たちは最初から両方のオーディエンスのために設計します。視界を遮らないカメラ位置、会場と配信で別々にミックスする音声、そして画面越しでも会場と同じように機能するコンテンツ設計です。', '専任のテクニカルディレクターが、会場運営チームとは独立してリモート配信を管理するため、一方でのトラブルがもう一方に波及することはありません。']::text[],
  capabilities_ja = ARRAY['会場・配信の両オーディエンス向け技術・コンテンツ設計', '会場運営チームと配信チームの独立した体制', 'リモート登壇者・パネルディスカッションの統合', '冗長化された配信インフラ', 'リモート参加者向けインタラクティブツール', '会場・リモート双方向けの同時通訳']::text[],
  process_ja = '[{"title":"両オーディエンス設計","description":"会場と配信の両方を前提にコンテンツと技術プランを構築します。"},{"title":"インフラ構築","description":"冗長化された配信経路と会場内AVをそれぞれ独立して構築・テストします。"},{"title":"本番技術リハーサル","description":"サウンドチェックではなく、実際の配信プラットフォームでの本番同様リハーサルを行います。"},{"title":"本番運営","description":"専任チームによる会場運営と配信ディレクションを並行して実施します。"}]'::jsonb,
  ideal_for_ja = ARRAY['リモート参加トラックのあるカンファレンス', '複数タイムゾーンにまたがるグローバルタウンホール', 'ハイブリッド型プレスイベント', '株主・投資家向け説明会']::text[],
  seo_title_ja = '日本国内のハイブリッドイベント制作サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国でハイブリッドイベント制作に対応。会場とリモートの両オーディエンスを一つのイベントとして設計し、冗長化された配信と専任の配信ディレクションを提供します。'
where slug = 'hybrid-events';

update services set
  name_ja = 'ライブ配信',
  short_description_ja = '冗長化されたインフラと専任のテクニカルディレクションによる、放送品質のライブ配信。',
  hero_statement_ja = '「ライブ」を絶対条件として扱う配信インフラ。',
  overview_ja = ARRAY['配信の途切れは、他のどんな制作トラブルよりも明確に見えてしまう失敗です。私たちはデュアル回線、バックアップエンコードパス、そして会場運営とは別に配信のみを監視する専任テクニカルディレクターなど、冗長性を標準として配信インフラを構築します。', 'シングルカメラでのウェブキャストから本格的なマルチカメラ放送ディレクションまで対応し、視聴者が既に使い慣れたプラットフォームに統合します。新しいツールを強いることはありません。']::text[],
  capabilities_ja = ARRAY['マルチカメラのライブ制作とスイッチング', '冗長化されたインターネット回線・エンコードパス', 'プラットフォーム統合（YouTube Live、Vimeo、カスタムRTMP、ウェビナーツール）', 'ライブグラフィックス・テロップ・コンテンツオーバーレイ', '多言語音声チャンネル配信', '収録・編集・オンデマンド納品']::text[],
  process_ja = '[{"title":"プラットフォーム・冗長化計画","description":"配信先プラットフォームを確認し、計画段階から冗長性を組み込みます。"},{"title":"技術施工","description":"カメラ・エンコード・ネットワークインフラを設営し、負荷テストを実施します。"},{"title":"本番プラットフォームでのリハーサル","description":"ローカルテストではなく、実際の配信先でのリハーサルを行います。"},{"title":"本番配信","description":"イベントを通じて専任のテクニカルディレクションが配信を監視します。"}]'::jsonb,
  ideal_for_ja = ARRAY['カンファレンス・基調講演の配信', '記者会見の放送', '授賞式・式典の配信', '多言語放送プログラム']::text[],
  seo_title_ja = '日本国内のライブ配信・放送サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国で放送品質のライブ配信に対応。冗長化されたインフラ、マルチカメラディレクション、専任の技術監視まであらゆる規模のイベントを支援します。'
where slug = 'live-streaming';

update services set
  name_ja = 'LEDソリューション',
  short_description_ja = '視聴距離とピッチに合わせて設計する、屋内外LEDウォールの設計・リギング・コンテンツ再生。',
  hero_statement_ja = '棚から借りるだけのLEDではなく、会場に合わせて仕様設計するLED。',
  overview_ja = ARRAY['不適切なピクセルピッチやパネルサイズの選定は、イベント制作において最もよくある、そして最も目につきやすい失敗の一つです。私たちは在庫にあるものをそのまま使うのではなく、実際の視聴距離、コンテンツ、会場に合わせてLEDを仕様設計します。', '近距離で見るステージ背景用のファインピッチ屋内ウォールから、式典や販促イベント向けの防水屋外スクリーンまで、リギング・キャリブレーション・コンテンツ再生を一体のサービスとして提供します。']::text[],
  capabilities_ja = ARRAY['視聴距離に合わせたピクセルピッチの仕様設計', '屋内外対応・防水LEDシステム', '曲面・角度付き・カスタム形状のLED構成', 'リギングエンジニアリングと構造荷重の承認', 'コンテンツ再生とメディアサーバー運用', '現地でのキャリブレーション・色調整']::text[],
  process_ja = '[{"title":"視認性・コンテンツ確認","description":"視界、視聴距離、コンテンツ種別を確認し適切なピッチを仕様化します。"},{"title":"リギング設計","description":"会場と機材の制限に対して構造リギングを設計・荷重確認します。"},{"title":"施工・キャリブレーション","description":"開場前にパネルの設営、キャリブレーション、色調整を行います。"},{"title":"本番運用","description":"弊社の技術者がメディアサーバーと再生を本番中操作します。"}]'::jsonb,
  ideal_for_ja = ARRAY['ステージ背景・基調講演用スクリーン', '展示会・ブース用ウォール', '屋外式典・販促イベント', '放送・カメラ向けディスプレイ']::text[],
  seo_title_ja = '日本国内のLEDウォールレンタル・ソリューション | TOTAL MEDIA',
  seo_description_ja = '日本全国で屋内外LEDウォールソリューションを提供。ピッチ仕様設計、リギングエンジニアリング、本番中のコンテンツ再生までステージ・ブース・屋外イベントに対応します。'
where slug = 'led-solutions';

update services set
  name_ja = '音響ソリューション',
  short_description_ja = '会場の音響特性とプログラム内容に合わせて設計する、ラインアレイPA・デジタルミキシング・通訳音声。',
  hero_statement_ja = '良い音響は気づかれません。問題があるときにだけ気づかれます。',
  overview_ja = ARRAY['良い音響は目立ちません。均一な音圧分布、ハウリングのない、スピーチにも音楽にもクリアに聞き取れる音です。私たちは会場の音響特性と具体的なプログラムに合わせてPA・ミキシングシステムを設計します。基調講演とライブバンドでは、同じシステムの音量を上下させるだけでは対応できません。本質的に異なるシステムが必要です。', '失敗するまで見過ごされがちな音響インフラ、通訳チャンネル、電波の混雑する会場でのワイヤレスマイク調整、放送・収録用のクリーンな音声フィードにも対応します。']::text[],
  capabilities_ja = ARRAY['会場の音響特性に合わせたラインアレイPA設計', 'デジタルミキシング・モニターシステム', 'ワイヤレスマイクの電波調整', '同時通訳音声の配信', '放送・収録用の音声フィード', 'ライブサウンドエンジニアリング・ミキシング']::text[],
  process_ja = '[{"title":"会場・プログラム確認","description":"システム仕様設計前に会場の音響特性とプログラム内容を確認します。"},{"title":"システム設計","description":"音圧の死角や電波干渉を避けるようPA・ミキシング・電波計画を設計します。"},{"title":"施工・チューニング","description":"その会場に合わせてシステムを設営し、音響チューニングを行います。"},{"title":"本番ミキシング","description":"システムを放置せず、専任エンジニアが本番中ライブでミキシングします。"}]'::jsonb,
  ideal_for_ja = ARRAY['カンファレンス・基調講演の音響', '通訳を伴う多言語イベント', 'ライブ音楽・エンターテインメントプログラム', '放送・収録イベント']::text[],
  seo_title_ja = '日本国内のイベント音響システム・ソリューション | TOTAL MEDIA',
  seo_description_ja = '日本全国でラインアレイPA、デジタルミキシング、通訳音声ソリューションを提供。会場の音響特性に合わせてライブ音響技術者が設計します。'
where slug = 'audio-solutions';

update services set
  name_ja = '照明ソリューション',
  short_description_ja = 'その瞬間を単に照らすだけでなく、演出として支えるステージ・空間・雰囲気照明の設計。',
  hero_statement_ja = '照明は、誰かが一言も話す前に、その場のトーンを決めます。',
  overview_ja = ARRAY['照明は、誰かが話す前に、フォーマルさ・熱量・親密さを会場に伝える最も速い手段です。それでいて、標準的なイベントパッケージの中で最も仕様が軽視されがちな要素の一つでもあります。私たちは照明を単なる一様な明かりではなく、物語を伝えるツールとして設計します。', '照明デザイナーが進行台本に沿ってキューをプログラムするため、基調講演からパネルディスカッションへ、プレゼンテーションからお披露目へといった場面転換が、スライドの切り替えだけでなく光によっても示されます。']::text[],
  capabilities_ja = ARRAY['ステージ・基調講演の照明設計', 'ムービングライト・建築照明のプログラミング', '進行台本に連動したキューベースの照明', '放送・配信向けのカメラマッチ照明', '会場空間の雰囲気照明・案内照明', 'コンソールプログラミングと本番運用']::text[],
  process_ja = '[{"title":"ムード・キュー計画","description":"進行台本と各場面に必要なトーンに合わせて照明キューを設計します。"},{"title":"設計・機材計画","description":"会場とプログラムに合わせて機材選定とリギング計画を作成します。"},{"title":"プログラミング","description":"開場前に、実際の進行台本に沿ってキューをプログラム・テストします。"},{"title":"本番運用","description":"照明オペレーターが本番中キューを操作し、必要に応じてリアルタイムで調整します。"}]'::jsonb,
  ideal_for_ja = ARRAY['基調講演・ステージ照明', '製品お披露目・発表会照明', '授賞式のプレゼンテーション照明', '会場の雰囲気照明・ガラディナー照明']::text[],
  seo_title_ja = '日本国内のイベント照明デザイン・ソリューション | TOTAL MEDIA',
  seo_description_ja = '日本全国でステージ・空間・雰囲気照明ソリューションを提供。プロの照明オペレーターが進行台本に合わせてキューベースの照明を設計します。'
where slug = 'lighting-solutions';

update services set
  name_ja = 'ステージ制作',
  short_description_ja = '会場とプログラムの要件に合わせて設計する、モジュール式ステージ・セット施工・構造リギング。',
  hero_statement_ja = 'ステージは、他のすべてが乗るインフラそのものです。',
  overview_ja = ARRAY['LED、照明、音響、カメラといった他のあらゆる技術要素は、ステージが構造的に健全で、適切なサイズであり、会場の実際の制約に合わせて施工されていることが前提となります。私たちはステージ施工をまずエンジニアリングとして、次にデザインとして扱いますが、どちらも妥協しません。', 'シンプルなプレゼンテーション用プラットフォームから、LEDやリギングを統合した多層構造のセットまで、プログラムに合わせてモジュール式ステージデッキ、カスタムセット要素、リギングシステムを施工します。']::text[],
  capabilities_ja = ARRAY['モジュール式ステージデッキ・雛壇システム', 'カスタムセットのデザイン・施工', '会場の荷重制限に合わせた構造リギング', '多層構造・ランウェイ型ステージ構成', '楽屋・早着替え用インフラ', '短納期対応の迅速な施工クルー']::text[],
  process_ja = '[{"title":"会場・荷重確認","description":"設計前に会場の床荷重、リギングポイント、搬入経路を確認します。"},{"title":"構造設計","description":"プログラム要件に合わせてステージ・セットを設計し、構造的に承認します。"},{"title":"施工","description":"搬入時間に合わせたスケジュールで統率されたクルーが施工します。"},{"title":"撤収","description":"会場の搬出要件に合わせて計画的に撤収します。"}]'::jsonb,
  ideal_for_ja = ARRAY['基調講演・カンファレンスステージ', '授賞式・ガラディナーのステージ', '製品発表会セット', '見本市のメインステージ']::text[],
  seo_title_ja = '日本国内のステージ制作・セット施工 | TOTAL MEDIA',
  seo_description_ja = '日本全国でモジュール式ステージ、カスタムセット施工、構造リギングを提供。会場の荷重制限に合わせて設計し、短納期の搬入出にも対応します。'
where slug = 'stage-production';

update services set
  name_ja = '技術制作',
  short_description_ja = 'LED・音響・照明・ステージ・カメラシステムを、一つの統合された分野として技術ディレクションします。',
  hero_statement_ja = '技術面の全体像に責任を持つ人が必要です。それがこのサービスです。',
  overview_ja = ARRAY['イベントにおける技術的なトラブルの多くは、各分野の境目で発生します。カメラの露出と衝突する照明、映像の遅延と同期していない音声、LEDチームと照明チームの間で調整されていないリギングなどです。技術制作とは、その境目に責任を持つ分野です。', 'LED、音響、照明、ステージ、カメラといったすべてのシステムを一つの統合された施工として調整するテクニカルディレクターを配置し、自社の機材インベントリと各分野の専門クルーで支えます。']::text[],
  capabilities_ja = ARRAY['制作全体に責任を持つ単一のテクニカルディレクター', '分野横断の調整（LED、音響、照明、ステージ、カメラ）', '電源分配・インフラ計画', 'システム横断の技術リハーサル・キュー統合', '現地での技術トラブルシューティング・コンティンジェンシー管理', 'イベント後の技術レポート']::text[],
  process_ja = '[{"title":"技術要件整理","description":"イベントに必要なすべての技術分野を一つの計画にまとめます。"},{"title":"統合設計","description":"キュー・電源・リギングが分野を越えて整合するようシステムを一体で設計します。"},{"title":"本番技術リハーサル","description":"個別ではなく、すべてのシステムを統合してテストします。"},{"title":"本番技術ディレクション","description":"単一のテクニカルディレクターが実行とコンティンジェンシーをリアルタイムで統括します。"}]'::jsonb,
  ideal_for_ja = ARRAY['あらゆる形式の複数分野にまたがる制作', '複雑なリギング・電源要件のあるイベント', '放送を統合したライブイベント', '単一の技術窓口を求めるクライアント']::text[],
  seo_title_ja = '日本国内の技術制作サービス | TOTAL MEDIA',
  seo_description_ja = '日本全国で統合技術制作を提供。単一のテクニカルディレクターがLED、音響、照明、ステージ、カメラシステムを一体の施工として調整します。'
where slug = 'technical-production';

update services set
  name_ja = 'イベントコンサルティング',
  short_description_ja = '社内にAVの専門知識を持たないチーム向けの、独立した技術・制作コンサルティング。',
  hero_statement_ja = '本契約の前にアドバイスすることが、最も役に立つ場合もあります。',
  overview_ja = ARRAY['すべての案件が、フル制作の施工から始まる必要はありません。会場の評価、予算感の把握、「ハイブリッド」に実際何が必要かの検討など、企画の初期段階にあるチーム向けに、契約前に技術面を整理するための単独コンサルティングを提供します。', '会場の技術評価、予算スコーピング、RFP・ベンダー選定資料の支援、そして他社ベンダーや社内チームが作成した技術プランのセカンドオピニオンレビューを含みます。']::text[],
  capabilities_ja = ARRAY['会場の技術評価・現地視察', '予算スコーピング・技術的実現可能性のレビュー', 'RFP・ベンダー選定資料への技術的助言', '既存の技術プランのセカンドオピニオンレビュー', '形式（対面・ハイブリッド・バーチャル）に関するガイダンス', '複数ベンダーが関わるイベントの調整アドバイス']::text[],
  process_ja = '[{"title":"ヒアリング","description":"イベント内容、制約条件、そして貴社が下そうとしている判断を理解します。"},{"title":"評価","description":"ご要望に応じて会場レビュー、予算スコーピング、プランレビューを実施します。"},{"title":"書面での提言","description":"自社サービスの売り込みではなく、明確で実行可能な提言をお渡しします。"},{"title":"任意のフォローアップ","description":"ご希望があれば、そのコンサルティング内容を提案のベースとして制作を実行します。"}]'::jsonb,
  ideal_for_ja = ARRAY['初めてハイブリッドイベントを企画するチーム', '専任のAV担当者がいない社内チーム', 'RFP・ベンダー選定プロセス', '既存の技術プランのセカンドオピニオン']::text[],
  seo_title_ja = '日本国内のイベント技術コンサルティングサービス | TOTAL MEDIA',
  seo_description_ja = '日本全国で独立系イベント技術コンサルティングを提供。社内にAV専門知識のないチーム向けに、会場評価、予算スコーピング、セカンドオピニオンレビューを行います。'
where slug = 'event-consultation';

update solutions set
  name_ja = 'ハイブリッド&バーチャルイベントソリューション',
  short_description_ja = '会場参加者とリモート参加者を一つの制作として運営する、プラットフォーム選定からライブ配信ディレクションまでのパッケージソリューション。',
  hero_statement_ja = 'オーディエンスが一つの会場に収まらない組織のために。',
  overview_ja = ARRAY['ハイブリッド・バーチャル形式は単一のサービスではありません。イベント企画、技術制作、ライブ配信、そして多くの場合通訳が一つの連鎖として組み合わさり、どこか一つに隙間があれば、それは本番中にオーディエンスの前で露呈します。', 'このソリューションは、ハイブリッド・バーチャルイベントを確実なものにする各分野をまとめて提供します。両オーディエンス向けのコンテンツ設計、冗長化された配信インフラ、そして配信のみに責任を持つテクニカルディレクターが、会場運営チームの代わりではなく、共に機能します。']::text[],
  highlights_ja = '[{"title":"両オーディエンス設計","description":"後から調整するのではなく、初日から会場と配信の両方を前提にコンテンツとカメラプランを構築します。"},{"title":"冗長化インフラ","description":"デュアル回線とバックアップエンコードパスをオプションではなく標準で提供します。"},{"title":"独立した配信ディレクション","description":"会場のステージマネジメントとは別に、配信専任のテクニカルディレクターを配置します。"},{"title":"通訳対応","description":"会場・リモート双方のオーディエンス向けに同時通訳チャンネルを配信に組み込みます。"}]'::jsonb,
  seo_title_ja = '日本国内のハイブリッド&バーチャルイベントソリューション | TOTAL MEDIA',
  seo_description_ja = '日本全国でハイブリッド・バーチャルイベントのパッケージソリューションを提供。両オーディエンス設計、冗長化配信、独立した配信ディレクションを組み合わせます。'
where slug = 'hybrid-virtual-solutions';

update solutions set
  name_ja = '大型ビジュアル&LEDソリューション',
  short_description_ja = 'LED・プロジェクション・照明を別々に調達するのではなく、一つのビジュアルシステムとして統合設計します。',
  hero_statement_ja = 'ビジュアルのスケール感そのものが目的となるイベントのために。',
  overview_ja = ARRAY['基調講演の背景、展示会の目玉展示、屋外式典のスクリーンといった大型ビジュアル演出は、同じステージに向けて別々にレンタルされた3つの機材ではなく、LED・照明・プロジェクションが一つの統合されたシステムとして機能することに支えられています。', 'このソリューションは、ピッチ仕様設計されたLED、キューベースの照明設計、リギングエンジニアリングを一つのビジュアル制作計画に統合し、オーディエンスが同時に目にするすべての要素で色・明るさ・キューの一貫性を保ちます。']::text[],
  highlights_ja = '[{"title":"統合ビジュアルシステム","description":"LED・照明・プロジェクションを個別ではなく一体で仕様設計・キャリブレーションします。"},{"title":"一体施工のリギング","description":"同じトラスを共有するすべてのビジュアル要素にわたって構造荷重を計算します。"},{"title":"コンテンツ・キュー統合","description":"メディア再生と照明キューを同じ進行台本に同期させます。"},{"title":"屋内外対応","description":"会場外での式典・販促イベント向けに防水オプションを用意します。"}]'::jsonb,
  seo_title_ja = '日本国内の大型LED・ビジュアルソリューション | TOTAL MEDIA',
  seo_description_ja = '日本全国で大型ビジュアルソリューションを提供。LED、照明、リギングを一つの統合されたビジュアルシステムとして設計します。'
where slug = 'large-format-visual-solutions';

update solutions set
  name_ja = '放送&配信ソリューション',
  short_description_ja = 'テレビ品質の映像出力が求められるイベント向けに、マルチカメラ放送制作と冗長化ライブ配信をパッケージ化。',
  hero_statement_ja = '参加されると同時に、視聴されるイベントのために。',
  overview_ja = ARRAY['授賞式、製品お披露目、プレスイベントは、会場で起きていることだけでなく、カメラが捉える映像によってますます評価が左右されるようになっています。このソリューションは、マルチカメラディレクション、放送品質の音声、冗長化配信を一つの制作分野として統合します。', '配信インフラに加えて、映像スイッチング、ライブグラフィックス、多言語音声チャンネルも対応するため、放送出力は固定カメラをステージに向けただけの映像ではなく、演出されたプロダクションになります。']::text[],
  highlights_ja = '[{"title":"マルチカメラディレクション","description":"放送経験を持つカメラオペレーターが映像スイッチングと画作りを担当します。"},{"title":"冗長化配信","description":"放送に関わる重要な工程にはデュアル回線とバックアップエンコードを標準で用意します。"},{"title":"ライブグラフィックス・オーバーレイ","description":"テロップ、ブランディング、多言語字幕を本番中にリアルタイムで統合します。"},{"title":"プラットフォーム非依存","description":"独自ツールではなく、オーディエンスが既に使っているプラットフォームで配信します。"}]'::jsonb,
  seo_title_ja = '日本国内の放送・ライブ配信ソリューション | TOTAL MEDIA',
  seo_description_ja = '日本全国で放送・配信ソリューションを提供。マルチカメラディレクション、冗長化配信、ライブグラフィックスまでテレビ品質の映像出力を実現します。'
where slug = 'broadcast-streaming-solutions';

update solutions set
  name_ja = 'フルサービス技術制作ソリューション',
  short_description_ja = 'LED・音響・照明・ステージ・リギング・カメラのすべての技術分野を、単一のテクニカルディレクターの下に統合します。',
  hero_statement_ja = '調整作業そのものがリスクとなるほど大規模なイベントのために。',
  overview_ja = ARRAY['一定の規模を超えると、イベントにおける最大のリスクは単一の技術システムではなく、それらの間の調整そのものになります。LEDの電力消費と競合する照明への電源配分。音響チームが既に確保していた視界を遮るカメラ位置。二つのベンダー間で二重予約されたリギングポイント。', 'このソリューションは、すべての技術分野を単一のテクニカルディレクターと一つの統合施工計画の下に置き、外部委託の寄せ集めではなく自社の機材インベントリで支えます。システム間の境目は、貴社ではなく私たちの責任です。']::text[],
  highlights_ja = '[{"title":"単一のテクニカルディレクター","description":"現地のすべての技術分野に対して単一の責任者を配置します。"},{"title":"統合施工計画","description":"LED・音響・照明・ステージにわたって電源・リギング・キューを一体で計画します。"},{"title":"自社機材インベントリ","description":"外部委託の寄せ集めではなく、自社カタログから機材を調達します。"},{"title":"コンティンジェンシー対応","description":"バックアップシステムと、本番中に問題解決できる権限を持つ技術チームを用意します。"}]'::jsonb,
  seo_title_ja = '日本国内のフルサービス技術制作ソリューション | TOTAL MEDIA',
  seo_description_ja = '日本全国でフルサービス技術制作ソリューションを提供。LEDからリギング、カメラまで、すべての分野を単一のテクニカルディレクターが統括します。'
where slug = 'full-service-technical-solutions';
