-- Bilingual _ja/_en columns for the taxonomy tables: equipment_categories,
-- blog_categories, faqs, industries. Same pattern as
-- 0017_i18n_services_solutions.sql — see that file's header for the twin-
-- column rationale. Generated by
-- scripts/generate-i18n-migration-taxonomy.ts — do not hand-edit the
-- UPDATE statements below; change the source content files and regenerate.


alter table equipment_categories rename column name to name_en;
alter table equipment_categories add column name_ja text;

alter table equipment_categories rename column description to description_en;
alter table equipment_categories add column description_ja text;

alter table blog_categories rename column name to name_en;
alter table blog_categories add column name_ja text;

alter table faqs rename column question to question_en;
alter table faqs add column question_ja text;

alter table faqs rename column answer to answer_en;
alter table faqs add column answer_ja text;

alter table industries rename column name to name_en;
alter table industries add column name_ja text;

alter table industries rename column description to description_en;
alter table industries add column description_ja text;

alter table industries rename column use_cases to use_cases_en;
alter table industries add column use_cases_ja text[] not null default '{}';

-- Populate Japanese translations for already-seeded rows (matched by slug).

update equipment_categories set name_ja = '屋内LED', description_ja = 'ステージ背景、展示会ウォール、放送品質のディスプレイ向けのファインピッチ屋内LEDパネル。視聴距離に合わせてサイズとピッチを選定します。' where slug = 'indoor-led';

update equipment_categories set name_ja = '屋外LED', description_ja = '屋外ステージ、式典、日中でも視認できる大型ブランドアクティベーション向けの防水・高輝度LED。' where slug = 'outdoor-led';

update equipment_categories set name_ja = '音響システム', description_ja = '会場の広さとプログラム内容に合わせて仕様設計する、ラインアレイPA、モニターシステム、デジタルミキシング、ワイヤレスマイク、通訳音声。' where slug = 'audio';

update equipment_categories set name_ja = '照明システム', description_ja = 'ステージ照明、基調講演照明、会場の雰囲気照明向けのムービングライト、建築照明、コンソールプログラミング。' where slug = 'lighting';

update equipment_categories set name_ja = 'ステージ・セット', description_ja = '会場の荷重制限に合わせて設計された、モジュール式ステージ、デッキ、カスタムセット要素。設営と同じ速さで撤収できるよう構築します。' where slug = 'stage';

update equipment_categories set name_ja = 'トラス・リギング', description_ja = 'LED、照明、スピーカーアレイ向けの地上支持・電動リギングシステム。認定された荷重計算に基づき承認されます。' where slug = 'truss';

update equipment_categories set name_ja = 'プロジェクター', description_ja = 'ステージ背景、プロジェクションマッピング、大型会場でのリア・フロント投影向けの高輝度レーザープロジェクション。' where slug = 'projectors';

update equipment_categories set name_ja = 'ディスプレイ・サイネージ', description_ja = '案内表示、受付、展示会ブース、デジタルサイネージネットワーク向けの自立型・設置型ディスプレイ。' where slug = 'displays';

update equipment_categories set name_ja = 'カメラシステム', description_ja = '配信・収録・IMAG向けの放送用・PTZカメラシステム、映像スイッチング、ライブ制作キット。' where slug = 'cameras';

update equipment_categories set name_ja = '周辺機材・サポート', description_ja = '電源分配、ケーブル、ケース、そして制作を最初から最後まで支える技術サポートインフラ。' where slug = 'accessories';

update blog_categories set name_ja = 'イベント企画' where slug = 'event-planning';

update blog_categories set name_ja = '技術制作' where slug = 'technical-production';

update blog_categories set name_ja = '業界インサイト' where slug = 'industry-insights';

update blog_categories set name_ja = 'ハイブリッド&バーチャル' where slug = 'hybrid-virtual';

update blog_categories set name_ja = '会社ニュース' where slug = 'company-news';

update faqs set question_ja = 'TOTAL MEDIAはどのようなクライアントと取引していますか？', answer_ja = '外資系企業、日本企業、イベント・PR代理店、展示会主催者、官公庁、大学、ホテル・MICE施設、そして日本で事業を展開するラグジュアリーブランドなど、幅広いお客様にご利用いただいています。案件の約半数は海外の関係者が関わっており、バイリンガルのプロジェクトマネジメントはオプションではなく、すべての案件で標準対応です。' where slug = 'faq-who-we-work-with';

update faqs set question_ja = '東京以外でも対応可能ですか？', answer_ja = 'はい、対応可能です。東京・大阪・名古屋の主要コンベンションセンターから、地方の会場、ホテルの宴会場、全国の屋外会場まで、日本全国でイベントを実施しています。機材・クルーのロジスティクスは、単一都市ではなく全国対応を前提に構築しています。' where slug = 'faq-nationwide-coverage';

update faqs set question_ja = '見積もりはどのくらいで届きますか？', answer_ja = '「見積もりを依頼する」フォームからの標準的なご依頼には、1〜2営業日以内に詳細なご提案をお送りします。複数日にわたる案件やカスタム技術設計を伴うハイブリッド制作など複雑な案件は、概算ではなく初期技術プランもあわせて準備するため、通常3〜5営業日ほどいただいています。' where slug = 'faq-quote-turnaround';

update faqs set question_ja = '料金体系はどのようになっていますか？', answer_ja = '料金は、イベント形式、会場、期間、機材の仕様、必要な人員によって決まります。会議室のAVセットアップと2日間のハイブリッドカンファレンスでは根本的に異なる案件のため、一律料金はございません。すべての提案書で機材費・人件費・制作管理費を項目ごとに分けて明示していますので、内訳をご確認のうえ必要に応じてスコープを調整いただけます。' where slug = 'faq-pricing-basis';

update faqs set question_ja = 'お支払い条件を教えてください。', answer_ja = '多くの案件では、署名済みの提案書と、日程確定・機材およびクルー確保のための頭金をいただき、残額は契約で合意したスケジュール（通常はイベント前後）でお支払いいただきます。官公庁・大学のお客様は、通常の調達・請求サイクルに合わせて対応可能です。' where slug = 'faq-deposit-payment';

update faqs set question_ja = '制作チームなしで機材のみのレンタルは可能ですか？', answer_ja = 'はい、可能です。社内に技術スタッフがいらっしゃる場合や、既存の制作パートナーがいらっしゃる場合は、機材のみのレンタルもご利用いただけます。ただし、初めてご利用のお客様の多くは、当日サポートなしで不慣れな機材を操作するリスクに比べ、設営・運用・撤収を担当する弊社技術者を追加する費用は小さいと感じられています。' where slug = 'faq-equipment-only';

update faqs set question_ja = 'どのようなブランド・基準の機材を使用していますか？', answer_ja = 'LED、音響、照明、リギングの機材は放送・ツアーグレードの仕様で調達し、定期点検スケジュールに沿って維持管理し、寿命まで使い切るのではなく定期的に入れ替えています。各カテゴリーの詳しい仕様は機材カタログに掲載しており、ご提案の際に具体的な機種もご案内いたします。' where slug = 'faq-equipment-brands';

update faqs set question_ja = 'どのくらい前に予約すればよいですか？', answer_ja = '標準的な企業イベント・カンファレンスの場合、4〜6週間前にご相談いただければ、企画・会場調整・機材手配に十分な余裕を持って対応できます。大規模な展示会、授賞式、カスタムステージや海外ロジスティクスを伴うイベントの場合は、8〜12週間前が理想的です。スケジュールに余裕がある場合は短納期のご依頼にも対応可能ですので、まずはお気軽にご相談ください。対応可否を正直にお伝えします。' where slug = 'faq-lead-time';

update faqs set question_ja = '事前の現地視察は行いますか？', answer_ja = '構造リギング、大型LED、または初めて利用する会場が関わるイベントについては、技術的な現地視察、または詳細なフロアプラン・搬入経路のレビューを標準対応として必ず実施します。これにより、電源・動線・リギングの制約を当日の問題になる前に把握できます。' where slug = 'faq-venue-site-visit';

update faqs set question_ja = '一部または全体を英語で進行するイベントにも対応できますか？', answer_ja = 'はい、対応可能です。海外のお客様向けに、日本語・英語のバイリンガルプロジェクトマネジメントと現地コーディネーションを標準で提供しており、同時通訳ブース、多言語サイン、両言語での進行台本作成にも日常的に対応しています。' where slug = 'faq-international-language';

update faqs set question_ja = 'ライブ配信・ハイブリッドイベントの信頼性はどのように確保していますか？', answer_ja = 'すべてのハイブリッド・バーチャル制作は、冗長化されたインターネット回線、バックアップエンコードパス、そして会場運営とは別に配信のみを監視する専任テクニカルディレクターの体制で運用しています。そのため、一方の回線に問題が発生しても配信が停止することはありません。また、すべてのハイブリッドイベントで、サウンドチェックだけでなく実際の配信プラットフォームを使った本番同様の技術リハーサルを実施しています。' where slug = 'faq-hybrid-virtual-reliability';

update faqs set question_ja = '電源・リギングの安全性についてはどのように対応していますか？', answer_ja = 'すべての電源分配・構造リギングは、有資格の技術者が会場の規定荷重制限に基づいて設計・承認し、放送に関わる重要な工程には冗長回線を用意しています。これはコンプライアンス上の必須要件として扱っており、予算の都合で省略する項目ではありません。' where slug = 'faq-power-rigging-safety';

update faqs set question_ja = '単なる機材レンタル会社とTOTAL MEDIAの違いは何ですか？', answer_ja = '機材レンタルは私たちの事業の一部であり、事業そのものではありません。私たちのチームはイベントの企画、技術制作の設計、展示会・カンファレンスの現地運営、そして機材の操作までを担います。つまり、企画・ステージ・AV・配信をそれぞれ別のベンダーで調整する代わりに、責任を持つ単一のパートナーとしてご利用いただけます。' where slug = 'faq-what-makes-different';

update faqs set question_ja = '複数日にわたる大規模イベントの人員体制にも対応できますか？', answer_ja = 'はい、対応可能です。会議室での1名体制のサポートから、並行セッション・ライブ配信・同時通訳が同時進行する複数日・複数ホールの展示会をカバーするフルクルー体制まで、規模に応じて人員を編成します。' where slug = 'faq-staffing-scale';

update industries set
  name_ja = '外資系企業',
  description_ja = '日本市場への参入・拡大を進めるグローバル企業には、地域・グローバル基準のイベントを現地で確実に実行できるパートナーが必要です。会場慣習、許認可、言語、ベンダー慣行まで含めて対応します。',
  use_cases_ja = ARRAY['地域統括拠点の設立イベント・タウンホール', 'APAC営業キックオフ・パートナーカンファレンス', '日本市場向けにローカライズしたグローバルブランドキャンペーン']::text[]
where slug = 'international-companies';

update industries set
  name_ja = '日本企業',
  description_ja = '株主総会から全国代理店会議まで、社内外の関係者が期待する技術的な精度と静かな信頼性を、老舗の日本企業様にご提供しています。',
  use_cases_ja = ARRAY['株主総会・総会', '社内カンファレンス・代理店イベント', '新製品・新サービス発表会']::text[]
where slug = 'japanese-corporations';

update industries set
  name_ja = 'イベント・PR代理店',
  description_ja = '代理店様のクリエイティブとクライアントリレーションを支える技術制作パートナーとして、貴社のブランドの下、貴社の進行台本に沿って、摩擦なく対応します。',
  use_cases_ja = ARRAY['代理店主導イベント向けのホワイトレーベル技術制作', '短納期のアクティベーション・プレスイベント', '日本での制作パートナーを必要とするマルチマーケットキャンペーン']::text[]
where slug = 'event-agencies';

update industries set
  name_ja = '展示会主催者',
  description_ja = '見本市・展示会の主催者様には、会場ロジスティクス、出展社対応、大規模イベント特有の限られた搬入出時間を理解したパートナーが必要です。',
  use_cases_ja = ARRAY['コンベンションセンター規模の見本市', '複数ホールで並行プログラムを行う展示会', '出展ブース・パビリオンの技術サービス']::text[]
where slug = 'exhibition-organizers';

update industries set
  name_ja = '官公庁',
  description_ja = '公共機関のイベントには、企業案件とは大きく異なる調達・警備・プロトコル要件が伴います。私たちはその基準に沿って対応することを前提としています。',
  use_cases_ja = ARRAY['省庁・自治体のカンファレンス・フォーラム', 'パブリックコンサルテーション・記者会見', '国際サミット・外交イベント']::text[]
where slug = 'government-organizations';

update industries set
  name_ja = '大学・学術機関',
  description_ja = '学術シンポジウムから卒業式まで、大学のイベントは多数の参加者、厳格なスケジュール、そして遠隔参加者・卒業生向けのハイブリッド・ライブ配信を伴うことが多いのが特徴です。',
  use_cases_ja = ARRAY['国際シンポジウム・研究カンファレンス', '卒業式・学位授与式', 'オープンキャンパス・入試説明会']::text[]
where slug = 'universities';

update industries set
  name_ja = 'ホテル・MICE施設',
  description_ja = 'ホテル・会場チームの優先技術ベンダーとして、施設の運営を妨げることなく、館内基準を満たす機材・エンジニアリング・クルーを提供します。',
  use_cases_ja = ARRAY['主要イベント向けの宴会場・バンケットAVアップグレード', '優先ベンダーとしての技術パートナーシップ', 'コンベンション・カンファレンスセンターの制作サポート']::text[]
where slug = 'hotels';

update industries set
  name_ja = 'MICEクライアント',
  description_ja = 'ミーティング、インセンティブ、カンファレンス、展示会はそれぞれ異なる制作要件を持ちます。私たちは4種類すべてに同じテンプレートを適用するのではなく、形式ごとにスコープと人員を設計します。',
  use_cases_ja = ARRAY['ハイブリッド・サテライト参加者を伴うインセンティブプログラム', '複数日にわたるコングレス・コンベンション制作', '慎重さと精度が求められるエグゼクティブミーティング']::text[]
where slug = 'mice-clients';

update industries set
  name_ja = 'ラグジュアリーブランド',
  description_ja = 'ラグジュアリークライアント様は、ブランドそのものにふさわしい制作品質を求めます。洗練された照明とステージ、静かで統率の取れたクルー、そして技術的な粗が一切見えないことが条件です。',
  use_cases_ja = ARRAY['製品発表会・プレスプレビュー', '旗艦店オープニング・ブランド体験イベント', 'VIP・プレスイベントのホスピタリティ制作']::text[]
where slug = 'luxury-brands';
