-- Bilingual _ja/_en columns for equipment_items. Same pattern as
-- 0017_i18n_services_solutions.sql — see that file's header for the twin-
-- column rationale. specs stays jsonb (array of {label, value}); applications
-- stays text[]. Generated by scripts/generate-i18n-migration-equipment.ts —
-- do not hand-edit the UPDATE statements below; change src/content/equipment.ts
-- and regenerate instead.


alter table equipment_items rename column name to name_en;
alter table equipment_items add column name_ja text;

alter table equipment_items rename column summary to summary_en;
alter table equipment_items add column summary_ja text;

alter table equipment_items rename column description to description_en;
alter table equipment_items add column description_ja text;

alter table equipment_items rename column specs to specs_en;
alter table equipment_items add column specs_ja jsonb not null default '[]';

alter table equipment_items rename column applications to applications_en;
alter table equipment_items add column applications_ja text[] not null default '{}';

-- Populate Japanese translations for already-seeded rows (matched by slug).

update equipment_items set
  name_ja = 'P1.9 ファインピッチ屋内LED',
  summary_ja = '近距離視聴のステージ背景や放送向けディスプレイに適した超ファインピッチパネル。',
  description_ja = '自社最高精細の屋内ピッチで、オーディエンスやカメラがウォールに近い環境向けに仕様設計されています。放送背景、役員会議室のディスプレイ、前列から視聴されるステージコンテンツなどに適しています。継ぎ目のないキャビネット接合により、カメラのクローズアップにも耐えます。',
  specs_ja = '[{"label":"ピクセルピッチ","value":"1.9mm"},{"label":"輝度","value":"800 nits"},{"label":"キャビネットサイズ","value":"500 x 500mm"},{"label":"リフレッシュレート","value":"3840Hz"},{"label":"推奨視聴距離","value":"2m以上"}]'::jsonb,
  applications_ja = ARRAY['放送用背景', '役員会議室・ブリーフィングルームのディスプレイ', '近距離視聴のステージコンテンツ']::text[]
where slug = 'indoor-led-p1-9-fine-pitch';

update equipment_items set
  name_ja = 'P2.6 屋内LEDパネル',
  summary_ja = '最も導入実績の多い屋内ピッチ。標準的なステージ背景向けに画質とコストのバランスを取っています。',
  description_ja = '視聴距離が通常3メートル以上となる基調講演・カンファレンスのステージ背景向けの標準仕様です。軽量キャビネットとクイックロック式リギングにより、画質を損なうことなく施工時間を短縮します。',
  specs_ja = '[{"label":"ピクセルピッチ","value":"2.6mm"},{"label":"輝度","value":"1000 nits"},{"label":"キャビネットサイズ","value":"500 x 500mm"},{"label":"リフレッシュレート","value":"3840Hz"},{"label":"推奨視聴距離","value":"3m以上"}]'::jsonb,
  applications_ja = ARRAY['基調講演・カンファレンス背景', '展示会ブースウォール', '製品発表会ステージ']::text[]
where slug = 'indoor-led-p2-6-standard';

update equipment_items set
  name_ja = 'P3.9 屋内レンタルパネル',
  summary_ja = '視聴距離に余裕があり広めのピッチが許容される大型屋内ウォール向けの、高稼働率レンタルパネル。',
  description_ja = '展示ホールの目玉展示やガラディナーの背景など、視聴距離に余裕があり広めのピッチでも同等の視覚品質を低コスト・短工期で実現できる大型屋内ウォール向けに仕様設計されています。',
  specs_ja = '[{"label":"ピクセルピッチ","value":"3.9mm"},{"label":"輝度","value":"1200 nits"},{"label":"キャビネットサイズ","value":"500 x 1000mm"},{"label":"リフレッシュレート","value":"1920Hz"},{"label":"推奨視聴距離","value":"4m以上"}]'::jsonb,
  applications_ja = ARRAY['大型展示ホールウォール', 'ガラ・式典の背景', '複数パネルによる曲面構成']::text[]
where slug = 'indoor-led-p3-9-rental';

update equipment_items set
  name_ja = 'P3.9 屋外防水パネル',
  summary_ja = '日中でも視認できる、式典・販促イベント向けのIP65防水屋外パネル。',
  description_ja = '防水密閉構造で日中の視認性にも対応した、屋外式典・販促イベント・ステージ向けの標準パネルです。日差し・風・小雨の中でも中断なく稼働します。',
  specs_ja = '[{"label":"ピクセルピッチ","value":"3.9mm"},{"label":"輝度","value":"5500 nits"},{"label":"防水等級","value":"IP65（前面・背面）"},{"label":"キャビネットサイズ","value":"500 x 500mm"},{"label":"耐風荷重","value":"構造審査により個別設計"}]'::jsonb,
  applications_ja = ARRAY['屋外式典', 'ブランド販促イベント', 'フェスティバル・公開イベントのステージ']::text[]
where slug = 'outdoor-led-p3-9-weatherproof';

update equipment_items set
  name_ja = 'P4.8 屋外LEDスクリーン',
  summary_ja = '遠距離視聴と高輝度の日中環境に対応する大型屋外スクリーンシステム。',
  description_ja = '視聴距離が長くなる大規模屋外会場向けに構築されています。屋外式典の背景、大規模オーディエンス向けIMAGスクリーン、直射日光下でも視認できるブランドウォールなどに対応します。',
  specs_ja = '[{"label":"ピクセルピッチ","value":"4.8mm"},{"label":"輝度","value":"6000 nits"},{"label":"防水等級","value":"IP65（前面・背面）"},{"label":"キャビネットサイズ","value":"500 x 1000mm"},{"label":"推奨視聴距離","value":"6m以上"}]'::jsonb,
  applications_ja = ARRAY['大規模屋外式典', '大規模オーディエンス向けIMAGスクリーン', '屋外ブランド販促イベント']::text[]
where slug = 'outdoor-led-p4-8-screen';

update equipment_items set
  name_ja = 'P6.6 屋外LEDウォール',
  summary_ja = 'スタジアム規模の視聴距離と迅速な複数パネル設営に対応する、長距離視認性の屋外ウォール。',
  description_ja = '自社在庫の中で最も広い屋外ピッチです。非常に大規模なオーディエンスと長い視聴距離が想定され、輝度と同じくらい迅速な複数パネル施工が重要となる屋外フェスティバル、大規模式典、公開イベントに導入されます。',
  specs_ja = '[{"label":"ピクセルピッチ","value":"6.6mm"},{"label":"輝度","value":"6500 nits"},{"label":"防水等級","value":"IP65（前面・背面）"},{"label":"キャビネットサイズ","value":"500 x 1000mm"},{"label":"推奨視聴距離","value":"10m以上"}]'::jsonb,
  applications_ja = ARRAY['スタジアム規模の屋外イベント', '大規模公開式典', 'フェスティバルのメインステージスクリーン']::text[]
where slug = 'outdoor-led-p6-6-wall';

update equipment_items set
  name_ja = 'ラインアレイPAシステム',
  summary_ja = 'カンファレンス・式典空間全体に均一な音圧をもたらす、スケーラブルなラインアレイシステム。',
  description_ja = '中〜大規模会場向けの主力PAシステムです。ポイントソーススピーカーにありがちな音圧の偏りや死角なく、前方から後方まで均一なカバレッジをイベントごとに構成します。単一ハングから大規模ホール向けのフルステレオアレイまでスケール可能です。',
  specs_ja = '[{"label":"構成","value":"モジュール式ラインアレイ、会場に合わせてスケール可能"},{"label":"周波数特性","value":"38Hz〜20kHz"},{"label":"最大音圧レベル","value":"138dB（アレイ構成により変動）"},{"label":"リギング","value":"フライングまたはグラウンドスタック"}]'::jsonb,
  applications_ja = ARRAY['カンファレンス・基調講演ホール', '授賞式・ガラディナー', '多目的会場空間']::text[]
where slug = 'audio-line-array-pa';

update equipment_items set
  name_ja = 'デジタルミキシングコンソール',
  summary_ja = 'ライブミキシング、モニターミックス、放送フィードに対応するマルチチャンネルデジタルコンソール。',
  description_ja = 'すべてのイベントで専任エンジニアが操作するデジタルコンソールプラットフォームです。客席向けミキシング、登壇者向けモニターミックス、放送・収録用のクリーンな独立フィードを同時に対応できます。',
  specs_ja = '[{"label":"チャンネル数","value":"最大64入力チャンネル"},{"label":"出力","value":"客席・モニター・放送フィードを同時出力"},{"label":"冗長性","value":"デュアル電源、バックアップコンソールオプション"},{"label":"収録","value":"マルチトラックセッション収録対応"}]'::jsonb,
  applications_ja = ARRAY['ライブイベントのミキシング', '多言語通訳ルーティング', '放送・収録用フィード']::text[]
where slug = 'audio-digital-mixing-console';

update equipment_items set
  name_ja = 'ワイヤレスマイクシステム',
  summary_ja = '登壇者・パネリスト向けの、電波調整済みワイヤレスハンドヘルド・ラベリア・ヘッドセットマイク。',
  description_ja = '会場の電波環境に合わせてチャンネルごとに調整されたワイヤレスマイクシステムです。都市部の密集会場や、同じ周波数帯を共有する複数ベンダーが関わるイベントでよくある音切れ・干渉を防ぎます。',
  specs_ja = '[{"label":"チャンネルタイプ","value":"ハンドヘルド、ラベリア、ヘッドセット"},{"label":"電波調整","value":"会場ごとに周波数を調整"},{"label":"通信距離","value":"見通し最大100m"},{"label":"バッテリー管理","value":"現地充電ステーション対応の充電式"}]'::jsonb,
  applications_ja = ARRAY['パネルディスカッション・Q&A', '基調講演', '授賞式のプレゼンターマイク']::text[]
where slug = 'audio-wireless-microphone-system';

update equipment_items set
  name_ja = 'ムービングヘッドスポットライト',
  summary_ja = 'ステージ照明、ゴボ投影、ダイナミックなキュー制御に対応するプログラム可能なムービングスポット。',
  description_ja = 'ステージ・基調講演の照明設計における主力機材です。精密なゴボ投影、カラーチェンジ、進行台本に同期したキューベースの動作に対応し、控えめなキー照明からフル制作のキュー演出まで幅広く使用されます。',
  specs_ja = '[{"label":"出力","value":"800W LEDエンジン"},{"label":"カラー","value":"フルCMY + カラーホイール"},{"label":"ゴボホイール","value":"回転式2基＋固定式1基"},{"label":"制御プロトコル","value":"DMX / RDM"}]'::jsonb,
  applications_ja = ARRAY['ステージ・基調講演照明', '製品お披露目の演出キュー', '授賞式のプレゼンテーション照明']::text[]
where slug = 'lighting-moving-head-spot';

update equipment_items set
  name_ja = 'LEDウォッシュライト',
  summary_ja = 'ステージの雰囲気カラーと会場の建築照明向けの、広角ビームLEDウォッシュ。',
  description_ja = 'ステージや会場の照明デザインの基礎となる、広く均一なカラーウォッシュを提供します。ムービングスポットの背後・脇に配置して奥行きを出すほか、単体でガラディナー・レセプションの雰囲気照明としても使用します。',
  specs_ja = '[{"label":"出力","value":"300W RGBAL LEDアレイ"},{"label":"ビーム角","value":"10°〜60°ズーム"},{"label":"カラー","value":"フルRGBALミキシング"},{"label":"制御プロトコル","value":"DMX / RDM"}]'::jsonb,
  applications_ja = ARRAY['ステージの雰囲気ウォッシュ', '会場の建築照明', 'ガラディナー・レセプション照明']::text[]
where slug = 'lighting-led-wash';

update equipment_items set
  name_ja = '照明コンソール',
  summary_ja = '専任プログラマーが本番中操作する、キューベースの照明制御コンソール。',
  description_ja = 'すべての照明デザインの制御ハブです。事前に進行台本に沿ってキューをプログラムし、本番中は照明技術者がリアルタイムで進行に合わせて調整しながら操作します。',
  specs_ja = '[{"label":"制御容量","value":"最大4096 DMXチャンネル"},{"label":"キュー保存","value":"無制限のプログラム可能キュー"},{"label":"バックアップ","value":"冗長コンソールフェイルオーバー対応"},{"label":"ネットワーク","value":"Art-Net / sACN"}]'::jsonb,
  applications_ja = ARRAY['キューベースのステージ照明', '複数機材の建築照明制御', '放送同期照明プログラム']::text[]
where slug = 'lighting-console';

update equipment_items set
  name_ja = 'モジュール式ステージデッキシステム',
  summary_ja = 'あらゆる規模のステージに対応する、高さ調整可能なモジュール式デッキ。',
  description_ja = '会場とプログラムの要件に合わせて高さ・面積・形状を構成できる標準ステージデッキシステムです。シンプルなプレゼンテーション台から本格的な多層構造の制作ステージまで対応します。',
  specs_ja = '[{"label":"デッキサイズ","value":"2m x 1mモジュール"},{"label":"高さ範囲","value":"0.2m〜2.4m調整可能"},{"label":"積載荷重","value":"750kg/m²（分布荷重）"},{"label":"表面仕上げ","value":"滑り止め、放送用ブラック仕上げ"}]'::jsonb,
  applications_ja = ARRAY['基調講演・カンファレンスステージ', '授賞式のステージ', '多層構造の製品発表会セット']::text[]
where slug = 'stage-modular-deck';

update equipment_items set
  name_ja = 'ステージ雛壇プラットフォーム',
  summary_ja = 'パネルディスカッション、VIP席、カメラ位置向けの自立式雛壇プラットフォーム。',
  description_ja = 'パネル登壇者席、VIPテーブル、カメラ位置をメインフロアより一段高くするための、コンパクトな自立式プラットフォームです。メインステージほどの構造計画を必要とせず、迅速に設営できます。',
  specs_ja = '[{"label":"プラットフォームサイズ","value":"2m x 1m、単体または積み重ね可能"},{"label":"高さオプション","value":"0.2m、0.4m、0.6m"},{"label":"積載荷重","value":"500kg/m²（分布荷重）"},{"label":"設営時間","value":"1台あたり30分未満"}]'::jsonb,
  applications_ja = ARRAY['パネルディスカッション席', 'VIP・ヘッドテーブルの段上げ', 'カメラ台の設置位置']::text[]
where slug = 'stage-riser-platform';

update equipment_items set
  name_ja = 'ランウェイ・キャットウォークステージ',
  summary_ja = '製品お披露目、ファッション形式のプレゼンテーション、行進形式の演出向けの延長ランウェイステージ。',
  description_ja = '空間内の移動そのものが演出の一部となるイベント向けの、細長い形状の延長ステージです。製品お披露目のウォーク、ファッションショー形式の演出、授賞式の入場行進などに使用します。',
  specs_ja = '[{"label":"標準長さ","value":"8m、2m単位で延長可能"},{"label":"幅","value":"標準1.2m、1.8mオプションあり"},{"label":"高さ","value":"0.4m〜0.8m"},{"label":"表面仕上げ","value":"滑り止め、カメラ映えするマット仕上げ"}]'::jsonb,
  applications_ja = ARRAY['製品お披露目のウォーク演出', 'ファッション形式のプレゼンテーション', '授賞式の入場行進']::text[]
where slug = 'stage-runway';

update equipment_items set
  name_ja = 'ボックストラス地上支持システム',
  summary_ja = '会場に吊り込みポイントがない場合の、LED・照明・スピーカーアレイ向け自立型地上支持トラス。',
  description_ja = '会場に天井吊り込みポイントがない場合や、構造承認上、地上支持型のソリューションが望ましい場合に使用します。LED・照明・スピーカーの荷重を独立して支える、エンジニアリング設計されたボックストラスタワーとスパンです。',
  specs_ja = '[{"label":"トラス断面","value":"400mmおよび520mmボックストラス"},{"label":"最大スパン","value":"荷重と構成に応じて個別設計"},{"label":"積載容量","value":"構造審査により算出"},{"label":"ベースオプション","value":"ウェイトベースプレートまたはアウトリガー式スタビライザー"}]'::jsonb,
  applications_ja = ARRAY['天井吊り込み設備のない会場', '屋外ステージ構造', 'LED・スピーカー支持タワー']::text[]
where slug = 'truss-box-ground-support';

update equipment_items set
  name_ja = '電動チェーンホイスト',
  summary_ja = '精密な高さ制御が可能な、吊り込みLED・照明・スピーカーアレイ向けの電動リギングホイスト。',
  description_ja = '会場の吊り込みポイントからLEDウォール、照明トラス、ラインアレイスピーカーを吊り上げるための電動ホイストです。搬入時の高さ調整と、安全に制御された撤収を精密に行えます。',
  specs_ja = '[{"label":"積載容量","value":"1台あたり500kg〜1000kg"},{"label":"制御","value":"複数ホイスト同期制御システム"},{"label":"安全性","value":"認証済み荷重リミッターとセカンダリ安全ケーブル"},{"label":"速度","value":"微調整可能な可変速"}]'::jsonb,
  applications_ja = ARRAY['吊り込みLEDウォール', '吊り込み照明トラス', '吊り込みラインアレイスピーカーシステム']::text[]
where slug = 'truss-motorized-hoist';

update equipment_items set
  name_ja = 'トラスタワーシステム',
  summary_ja = '照明位置、ディレイスピーカー、屋外スクリーン支持向けの垂直トラスタワー。',
  description_ja = 'メインステージ構造とは独立して、照明機材の配置、ディレイスピーカーの設置、屋外LEDスクリーンの高所支持に使用する自立式垂直タワーです。',
  specs_ja = '[{"label":"高さ範囲","value":"3m〜12m、セクション式"},{"label":"基礎形式","value":"現場条件に応じてウェイトまたはガイワイヤー式"},{"label":"積載容量","value":"搭載機材の荷重に応じて算出"},{"label":"耐風性能","value":"屋外設営向けに構造設計"}]'::jsonb,
  applications_ja = ARRAY['屋外照明タワー', 'ディレイスピーカー設置位置', '屋外LEDスクリーンの支持']::text[]
where slug = 'truss-tower-system';

update equipment_items set
  name_ja = '20,000ルーメン レーザープロジェクター',
  summary_ja = '大規模会場の背景やプロジェクションマッピング向けの高輝度レーザープロジェクター。',
  description_ja = '自社最高出力のプロジェクターです。環境光の強い大規模会場、大型スクリーン、または凹凸のある面でも均一な輝度が求められるセットや建築物へのプロジェクションマッピング向けに仕様設計されています。',
  specs_ja = '[{"label":"輝度","value":"20,000ルーメン"},{"label":"解像度","value":"4K UHD（3840 x 2160）"},{"label":"光源","value":"レーザー蛍光体方式、定格寿命20,000時間"},{"label":"レンズオプション","value":"短焦点〜長焦点まで対応"}]'::jsonb,
  applications_ja = ARRAY['大規模会場のステージ背景', 'セットへのプロジェクションマッピング', '環境光の強い環境']::text[]
where slug = 'projector-20000-lumen-laser';

update equipment_items set
  name_ja = '10,000ルーメン レーザープロジェクター',
  summary_ja = '標準的なカンファレンス・プレゼンテーション環境向けの中出力レーザープロジェクター。',
  description_ja = '環境光が制御された標準的な会議室やプレゼンテーションステージに適した、汎用性の高い中出力プロジェクターです。コンテンツ・プレゼンテーション投影で最も導入実績の多い機種です。',
  specs_ja = '[{"label":"輝度","value":"10,000ルーメン"},{"label":"解像度","value":"4K UHD（3840 x 2160）"},{"label":"光源","value":"レーザー蛍光体方式、定格寿命20,000時間"},{"label":"レンズオプション","value":"標準ズームレンズ付属"}]'::jsonb,
  applications_ja = ARRAY['会議室でのプレゼンテーション', 'コンテンツ・スライド投影', '中規模会場の背景']::text[]
where slug = 'projector-10000-lumen-laser';

update equipment_items set
  name_ja = '短焦点プロジェクター',
  summary_ja = 'レンズの投影距離が確保できない狭い会場やステージ前方投影向けの短焦点機種。',
  description_ja = '床面積や天井高の制約で標準的なレンズ投影距離が確保できない環境に導入します。ブース環境、ステージ前方での近距離コンテンツ投影、プロジェクタースタンドをスクリーンから離せない空間などに対応します。',
  specs_ja = '[{"label":"輝度","value":"6,500ルーメン"},{"label":"解像度","value":"WUXGA（1920 x 1200）"},{"label":"投影比","value":"0.38:1"},{"label":"光源","value":"レーザー蛍光体方式"}]'::jsonb,
  applications_ja = ARRAY['展示会ブースでの投影', '狭小空間でのステージ前方コンテンツ', '天井高の低い会場環境']::text[]
where slug = 'projector-short-throw';

update equipment_items set
  name_ja = '55インチ デジタルサイネージディスプレイ',
  summary_ja = '案内表示、受付、インフォメーションポイント向けの自立型・設置型デジタルサイネージ。',
  description_ja = '受付デスク、案内表示ポイント、インフォメーションステーション向けの標準サイネージディスプレイです。フロアスタンドまたは壁掛けと、コンテンツ再生サポート付きで提供します。',
  specs_ja = '[{"label":"画面サイズ","value":"55インチ"},{"label":"解像度","value":"4K UHD"},{"label":"輝度","value":"500 nits"},{"label":"設置方式","value":"フロアスタンドまたは壁掛け"}]'::jsonb,
  applications_ja = ARRAY['受付・ウェルカムデスク', '案内表示・フロアガイド', 'スポンサー・アジェンダ表示']::text[]
where slug = 'displays-55-inch-signage';

update equipment_items set
  name_ja = '自立型タッチキオスク',
  summary_ja = '展示会での来場者エンゲージメントとセルフサービス受付向けのインタラクティブタッチスクリーンキオスク。',
  description_ja = '展示ブースでのエンゲージメント、セルフサービスチェックイン、インタラクティブコンテンツ向けのキオスクです。単体でも、会場フロア全体でネットワーク接続しても運用できます。',
  specs_ja = '[{"label":"画面サイズ","value":"32インチまたは43インチタッチディスプレイ"},{"label":"タッチ技術","value":"静電容量式マルチタッチ"},{"label":"接続性","value":"Wi-Fi / 有線LAN、ネットワーク対応"},{"label":"筐体","value":"自立型、ブランドラッピング対応可能"}]'::jsonb,
  applications_ja = ARRAY['展示ブースのエンゲージメント', 'セルフサービスチェックイン', 'インタラクティブ製品展示']::text[]
where slug = 'displays-touch-kiosk';

update equipment_items set
  name_ja = 'ビデオウォールディスプレイ',
  summary_ja = 'LEDではなく液晶パネルベースの大型ディスプレイを求める場合のモジュール式ビデオウォール。',
  description_ja = 'LEDの代替として、画面ベースの大型ディスプレイが望ましい屋内環境向けのモジュール式液晶ビデオウォールです。コンテンツ豊富な展示の目玉展示やロビーインスタレーションに使用します。',
  specs_ja = '[{"label":"構成","value":"2x2〜5x5のモジュールアレイ"},{"label":"ベゼル幅","value":"3.5mm 超狭額縁"},{"label":"解像度","value":"モジュールごとに4K UHD、タイリング表示"},{"label":"設置方式","value":"自立フレームまたは壁掛け"}]'::jsonb,
  applications_ja = ARRAY['展示会の目玉ディスプレイ', 'ロビー・レセプションインスタレーション', 'コンテンツ豊富な屋内ウォール']::text[]
where slug = 'displays-video-wall';

update equipment_items set
  name_ja = 'PTZカメラシステム',
  summary_ja = 'カメラごとの専任オペレーターなしで目立たないマルチアングル撮影を実現する、リモートパン・チルト・ズームカメラ。',
  description_ja = 'すべての撮影位置にオペレーターを配置することなく、オーディエンスショット、ステージ全体ショット、パネルのクローズアップなど撮影アングルを追加できるリモート制御PTZカメラです。中央のビジョンパネルから制御します。',
  specs_ja = '[{"label":"出力","value":"4K UHD / 1080p60"},{"label":"ズーム","value":"光学20倍"},{"label":"制御","value":"一元化されたPTZ制御パネル"},{"label":"設置方式","value":"天井・壁・三脚設置対応"}]'::jsonb,
  applications_ja = ARRAY['パネル・オーディエンス撮影', '目立たないマルチアングル撮影', 'ハイブリッド・配信制作']::text[]
where slug = 'camera-ptz-system';

update equipment_items set
  name_ja = '放送用カメラパッケージ',
  summary_ja = '授賞式、基調講演、ディレクション付きマルチカメラ制作向けの、オペレーター配置の放送用カメラ。',
  description_ja = '専任オペレーター付きのフル放送用カメラパッケージです。構図やディレクションが重要となる制作、授賞式、基調講演の撮影、そして番組として収録・配信されるあらゆるイベントに使用します。',
  specs_ja = '[{"label":"出力","value":"4K UHD放送用カメラ"},{"label":"クルー","value":"訓練されたカメラオペレーターが担当"},{"label":"レンズキット","value":"ズーム・単焦点レンズオプション"},{"label":"信号","value":"SDI／光ファイバーでビジョンスイッチャーへ伝送"}]'::jsonb,
  applications_ja = ARRAY['授賞式の撮影', '基調講演・ステージ放送', 'ディレクション付きマルチカメラ制作']::text[]
where slug = 'camera-broadcast-package';

update equipment_items set
  name_ja = 'ビジョンスイッチャー・配信キット',
  summary_ja = 'ライブ制作と配信出力向けのマルチカメラ映像スイッチング・エンコードキット。',
  description_ja = 'マルチカメライベントの制作ハブです。カメラフィード間のスイッチング、グラフィックス・テロップの統合、ライブ配信・放送用の最終番組エンコードを行います。',
  specs_ja = '[{"label":"入力","value":"最大8系統のカメラ・ソース入力"},{"label":"出力","value":"マルチプラットフォーム配信エンコード＋番組フィード"},{"label":"グラフィックス","value":"ライブテロップ・オーバーレイ統合"},{"label":"冗長性","value":"バックアップエンコーダーとデュアル回線"}]'::jsonb,
  applications_ja = ARRAY['ライブ配信制作', 'マルチカメライベントディレクション', 'ハイブリッドイベント放送']::text[]
where slug = 'camera-vision-switcher-kit';

update equipment_items set
  name_ja = '電源分配システム',
  summary_ja = 'あらゆる規模の技術負荷に対応する、認証済みの電源分配・回線管理。',
  description_ja = '会場の規定に準拠して設計・施工される電源分配システムで、放送に関わる重要な機器には冗長回線を割り当てます。私たちが導入するすべてのLED・音響・照明・カメラシステムの基盤となるインフラ層です。',
  specs_ja = '[{"label":"分配方式","value":"三相・単相分電盤"},{"label":"回路保護","value":"漏電遮断器保護、規定準拠"},{"label":"冗長性","value":"重要負荷向けの独立バックアップ回路"},{"label":"ケーブル管理","value":"定格ケーブルと配線経路の完全記録"}]'::jsonb,
  applications_ja = ARRAY['イベント全体の電源インフラ', '放送に関わる重要機器の冗長回路', '複数ベンダーが電源を共有する環境']::text[]
where slug = 'accessories-power-distribution';

update equipment_items set
  name_ja = 'ケーブルランプ・管理キット',
  summary_ja = '公共エリアを横断する配線を安全かつ美しく保つための、ケーブルランプ・配線処理・経路管理。',
  description_ja = '公共の通路やステージエリアを横断する電源・信号ケーブルを安全に配線するためのケーブルランプ・配線処理システムです。安全基準への準拠と、制作としての見た目の美しさの両方に関わる細部です。',
  specs_ja = '[{"label":"ランプ種類","value":"シングル、デュアル、5チャンネルケーブルランプ"},{"label":"耐荷重","value":"歩行者・軽車両対応"},{"label":"準拠基準","value":"会場・消防法の通路要件に適合"},{"label":"仕上げ","value":"高視認性・低背オプション"}]'::jsonb,
  applications_ja = ARRAY['公共通路の配線横断', '楽屋裏の配線処理', '展示会フロアの配線管理']::text[]
where slug = 'accessories-cable-management';

update equipment_items set
  name_ja = 'フライトケース・輸送パッケージ',
  summary_ja = '全国の会場間を移動する機材向けの、輸送グレードフライトケースと輸送ロジスティクス。',
  description_ja = '自社施設と全国の会場間、または複数都市にまたがるプログラムの複数会場間を移動する機材向けの、輸送グレードケースと連携した輸送ロジスティクスです。',
  specs_ja = '[{"label":"ケース規格","value":"輸送グレード、機材セットごとにフォーム加工"},{"label":"追跡管理","value":"ケース・イベントごとに在庫追跡"},{"label":"輸送","value":"全国規模のロジスティクス調整"},{"label":"保険","value":"輸送中の補償を含む"}]'::jsonb,
  applications_ja = ARRAY['複数都市を巡るイベントツアー', '全国規模の機材ロジスティクス', '安全な機材輸送・保管']::text[]
where slug = 'accessories-flight-cases';
